name: sim

inputs:
  - build

outputs:
  - run.saif

commands:
  - sh run.sh

parameters:
  clock_period: 5
  sim_level: rtl 
  # These parameters just need to exist for building the simulator
  network: resnet18
  layer: conv1
  data_dir: None
  sims: accelerator,customposit
  gen_saif: True
