# MINOTAUR CI
stages:
  - setup
  - test
  - check_results
  - cleanup

before_script:
  - eval `modulecmd bash load base catapult/2024.2_2 vcs/T-2022.06-SP2 verdi/S-2021.09-SP1 dc_shell/U-2022.12-SP1`
  - export VG_GNU_PACKAGE=/cad/synopsys/vcs_gnu_package/S-2021.09/gnu_9/linux
  - source /cad/synopsys/vcs_gnu_package/S-2021.09/gnu_9/linux/source_me.sh
  - export LD_LIBRARY_PATH=/cad/mentor/2024.2_2/Mgc_home/lib:/cad/mentor/2024.2_2/Mgc_home/shared/lib:$LD_LIBRARY_PATH
  - export PATH=$HOME/miniforge3/condabin:$PATH
  - source $(conda info --base)/etc/profile.d/conda.sh
  - conda activate ci-env-$CI_PIPELINE_ID
  - export PROJECT_ROOT=`pwd`
  - export CODEGEN_DIR=test/compiler

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 3
  GIT_CLEAN_FLAGS: -ffdx

include:
  - local: .gitlab/ci/conda_setup.yml
  - local: .gitlab/ci/rtl.yml
  - local: .gitlab/ci/accuracy.yml
  - local: .gitlab/ci/area.yml
  - local: .gitlab/ci/systemc.yml
  - local: .gitlab/ci/check_results.yml
  - local: .gitlab/ci/cleanup.yml