# MINOTAUR CI 

# We are using runners on "rsgvm9". 
# They can be configured using "/etc/gitlab-runner/config.toml".
# The working-dir of runners is "/home/gitlab-runner/builds".

stages:
  - init
  - build
  - test

init-job:
  stage: init
  script:
    - echo "-> New CI job started by $GITLAB_USER_LOGIN on runner $CI_RUNNER_DESCRIPTION ($CI_RUNNER_ID)."
    - echo "-> Running CI with commit $CI_COMMIT_DESCRIPTION ($CI_COMMIT_SHORT_SHA)."
    - date

data-job:
  stage: build
  script: 
    - echo "Generating test data."
    - echo "Not yet implemented..."

build-job:
  stage: build
  script: 
    - echo "Building accelerator."
    - echo "Not yet implemented..."

test-job:
  stage: test
  script: 
    - echo "Running tests."
    - echo "Not yet implemented..."
