import math
import os
import struct
import numpy as np

import torch
import torch.nn.functional as F

import argparse
import json

# This file is used to parse the .bin tensor files generated by the voyager compiler. It extracts the required tensors, (input, weight, bias, inputScale, weightScale)
# converts them from float32 to int8, bfloat16, and e8m0 formats, tranposes them to the required layout in memory, allocates GLB memory for each tensor, and writes them to hex files
# consumable by the AHA flow.

def read_tensor(filename, tensor_shape):
    with open(filename, 'rb') as f:
        file_content = f.read()

    num_elements = len(file_content) // struct.calcsize('f')
    print(f"INFO: Read {num_elements} elements from binary file {filename}")
    unpacked_data = struct.unpack(f'{num_elements}f', file_content)

    tensor = torch.tensor(unpacked_data).reshape(tensor_shape)
    return tensor


def float_to_e8m0(x):
    # Assume input is a float32 tensor
    x = x.cpu().numpy().astype(np.float32)
    bits = np.frombuffer(x.tobytes(), dtype=np.uint32)
    e8m0 = ((bits >> 23) & 0xFF)  # extract exponent only
    return e8m0


def float32_to_bfloat16_bits(x):
    # Step 1: Move to CPU and convert to NumPy float32
    np_fp32 = x.cpu().numpy().astype(np.float32)

    # Step 2: View as uint32
    np_uint32 = np_fp32.view(np.uint32)

    # Step 3: Extract top 16 bits (bfloat16 format)
    np_bf16_uint16 = (np_uint32 >> 16).astype(np.uint16)

    return np_bf16_uint16


def write_list_to_hex(list, filename, start_addr=0):
   #Write the entire tensor in hex format to a new file
   with open(filename, 'w') as output_file:
        output_file.write(f"SIZE: {len(list)}\n")
        output_file.write(f"START_ADDR: {start_addr}\n")
        for idx in range(len(list)):
            value = list[idx]
            output_file.write(str(f"{value:04x}"))
            if idx != len(list) - 1:
                output_file.write("\n")

def debug_print_tensors(
            input, input_int8, bias, bias_bf16, inputScale, inputScale_e8m0,
            weightScale, weightScale_e8m0, weight):
    # Print first 10 elements and max value
        print("First 10 elements of the input tensor:", input.flatten()[:10])
        print("Max value of the input tensor:", torch.max(input))

        print("First 10 elements of the input INT8 tensor:", input_int8.flatten()[:10])
        print("Max value of the input INT8 tensor:", torch.max(input_int8))

        print("First 10 elements of the bias tensor:", bias.flatten()[:10])
        print("Max value of the bias tensor:", torch.max(bias))

        print("First 10 elements of the bias bFloat16 tensor:", bias_bf16.flatten()[:10])
        print("First 10 elements of the inputScale tensor:", inputScale.flatten()[:10])
        print("Max value of the inputScale tensor:", torch.max(inputScale))
        print("Min value of the inputScale tensor:", torch.min(inputScale))

        print("First 10 elements of the inputScale e8m0 tensor:", inputScale_e8m0.flatten()[:10])

        print("First 10 elements of the weightScale tensor:", weightScale.flatten()[:10])
        print("Max value of the weightScale tensor:", torch.max(weightScale))
        print("Min value of the weightScale tensor:", torch.min(weightScale))

        print("First 10 elements of the weightScale e8m0 tensor:", weightScale_e8m0.flatten()[:10])

        print("First 10 elements of the weight tensor:", weight.flatten()[:10])
        print("Shape of the bytes object:", len(input_int8.numpy().tobytes()))

def write_all_tensors_to_hex(
        input_int8, weight_int8, bias_bf16, inputScale_e8m0, weightScale_e8m0,
        output_dir, input_start_addr=0, weight_start_addr=0, bias_start_addr=0,
        inputScale_start_addr=0, weightScale_start_addr=0,
        residual_start_addr="set by io_placement", has_residual=False, residual_bf16=None
    ):
        write_list_to_hex(input_int8.numpy().tobytes(), output_dir + 'input_hex.txt', input_start_addr)
        write_list_to_hex(weight_int8.numpy().tobytes(), output_dir + 'weight_hex.txt', weight_start_addr)
        write_list_to_hex(bias_bf16, output_dir + 'bias_hex.txt', bias_start_addr)
        write_list_to_hex(inputScale_e8m0, output_dir + 'inputScale_hex.txt', inputScale_start_addr)
        write_list_to_hex(weightScale_e8m0, output_dir + 'weightScale_hex.txt', weightScale_start_addr)
        if has_residual and residual_bf16 is not None:
            write_list_to_hex(residual_bf16, output_dir + 'residual_hex.txt', residual_start_addr)


# For writing partial sum output from a prior kernel to raw binary file
def hw_output_txt_to_raw(input_txt_path, output_raw_path):
    # Read the file content
    with open(input_txt_path, 'r') as f:
        hex_values = f.read().split()

    # Convert hex strings to unsigned 16-bit integers
    uint16_array = np.array([int(h, 16) for h in hex_values], dtype=np.uint16)

    # Swap byte order
    uint16_array_be = uint16_array.byteswap().newbyteorder('>')

    # Save to raw binary file
    uint16_array_be.tofile(output_raw_path)


def parse_zircon_workarounds():
    # Workarounds to avoid Zircon MU bug on Resnet downsample layers
    zircon_fx_fy_stride_workaround = "ZIRCON_FX_FY_STRIDE_WORKAROUND" in os.environ and os.environ["ZIRCON_FX_FY_STRIDE_WORKAROUND"] == "1"
    zircon_cgra_psum_workaround = "ZIRCON_CGRA_PSUM_WORKAROUND" in os.environ and os.environ["ZIRCON_CGRA_PSUM_WORKAROUND"] == "1"
    psum_idx = 0
    num_psums = 1
    if zircon_cgra_psum_workaround:
        assert "PSUM_IDX" in os.environ, "PSUM_IDX environment variable must be set for ZIRCON_CGRA_PSUM_WORKAROUND"
        assert "NUM_PSUMS" in os.environ, "NUM_PSUMS environment variable must be set for ZIRCON_CGRA_PSUM_WORKAROUND"
        psum_idx = int(os.environ["PSUM_IDX"])
        num_psums = int(os.environ["NUM_PSUMS"])

    # Input padding workaround for Zircon MU inability to handle some layer shapes
    zircon_input_padding_workaround = "ZIRCON_INPUT_PADDING_WORKAROUND" in os.environ and os.environ["ZIRCON_INPUT_PADDING_WORKAROUND"] == "1"
    zircon_input_padding_workaround_size = 0
    if zircon_input_padding_workaround:
        assert "ZIRCON_INPUT_PADDING_WORKAROUND_SIZE" in os.environ, "ZIRCON_INPUT_PADDING_WORKAROUND_SIZE environment variable must be set for ZIRCON_INPUT_PADDING_WORKAROUND"
        zircon_input_padding_workaround_size = int(os.environ.get("ZIRCON_INPUT_PADDING_WORKAROUND_SIZE"))

    # K dimension host tiling: used in resnet18 conv5 in Zircon
    k_dim_host_tiling = "K_DIM_HOST_TILING" in os.environ and os.environ["K_DIM_HOST_TILING"] == "1"
    num_k_host_tiling_kernels = 1
    k_dim_host_tiling_idx = 0
    if k_dim_host_tiling:
        assert "NUM_K_HOST_TILING_KERNELS" in os.environ, "NUM_K_HOST_TILING_KERNELS environment variable must be set for K_DIM_HOST_TILING"
        assert "K_DIM_HOST_TILING_IDX" in os.environ, "K_DIM_HOST_TILING_IDX environment variable must be set for K_DIM_HOST_TILING"
        num_k_host_tiling_kernels = int(os.environ.get("NUM_K_HOST_TILING_KERNELS"))
        k_dim_host_tiling_idx = int(os.environ.get("K_DIM_HOST_TILING_IDX"))

    if zircon_cgra_psum_workaround:
        print(f"\033[93mINFO: Zircon CGRA PSUM workaround enabled to avoid MU bug on downsample layers. Using PSUM index {psum_idx}. There are {num_psums} total PSUMs.\033[0m")

    if zircon_fx_fy_stride_workaround:
        print("\033[93mINFO: Zircon FX, FY stride workaround enabled to avoid MU bug on downsample layers.\033[0m")

    if zircon_input_padding_workaround:
        print(f"\033[93mINFO: Zircon input padding workaround enabled. Input image will be padded with +{zircon_input_padding_workaround_size}.\033[0m")

    if k_dim_host_tiling:
        print(f"\033[93mINFO: K dimension host tiling enabled. Using {num_k_host_tiling_kernels} kernels with index {k_dim_host_tiling_idx}.\033[0m")


    return zircon_fx_fy_stride_workaround, zircon_cgra_psum_workaround, psum_idx, num_psums, \
           zircon_input_padding_workaround, zircon_input_padding_workaround_size, \
           k_dim_host_tiling, num_k_host_tiling_kernels, k_dim_host_tiling_idx


def parse_tensors(model, layer, datatype, h2h_dir, debug_mode):
    # Base path for the binary files
    base_path = f'/aha/voyager/test/compiler/networks/{model}/{datatype}/tensor_files/'

    with open("/aha/voyager/tensor_metadata.json", "r") as f:
        tensor_metadata = json.load(f)

    has_residual = tensor_metadata["has_residual"]

    input_tensor_data = tensor_metadata["ops"][0]["kwargs"]["input"]["tensor"]
    weight_tensor_data = tensor_metadata["ops"][0]["kwargs"]["weight"]["tensor"]
    bias_tensor_data = tensor_metadata["ops"][0]["kwargs"]["bias"]["tensor"]
    inputScale_tensor_data = tensor_metadata["ops"][0]["kwargs"]["input_scale"]["tensor"]
    weightScale_tensor_data = tensor_metadata["ops"][0]["kwargs"]["weight_scale"]["tensor"]

    if has_residual:
        all_op_names = []
        for op in tensor_metadata["ops"]:
            all_op_names.append(op["name"])

        for op in tensor_metadata["ops"]:
            if "add" in op["name"]:
                for key in op["kwargs"]:
                    if "tensor" in op["kwargs"][key]:
                        # Slightly fragile, but we assume the residual tensor is the one that is not in the list of all op names
                        # May need to revisit this in the future...
                        if op["kwargs"][key]["tensor"]["node"] not in all_op_names:
                            residual_tensor_data = op["kwargs"][key]["tensor"]
                            break

    mu_glb_base_addr = tensor_metadata["mu_glb_base_address"]


    zircon_fx_fy_stride_workaround, zircon_cgra_psum_workaround, psum_idx, num_psums, \
    zircon_input_padding_workaround, zircon_input_padding_workaround_size, \
    k_dim_host_tiling, num_k_host_tiling_kernels, k_dim_host_tiling_idx = parse_zircon_workarounds()

    # INPUT
    # Shape is in format: (OC, IC, Y, X)
    input = read_tensor(base_path + input_tensor_data["node"] + ".bin",
                        (input_tensor_data["shape"][0], input_tensor_data["shape"][1], input_tensor_data["shape"][2], input_tensor_data["shape"][3]))
    if zircon_input_padding_workaround:
        input = F.pad(input, pad=(0, zircon_input_padding_workaround_size, 0, zircon_input_padding_workaround_size)) # Pad X and Y dimensions with zeros
    # Re-order it so IC is the innermost dimension (Y, X, OC, IC)
    input_reordered = input.permute(2, 3, 0, 1)
    if zircon_cgra_psum_workaround:
        input_reordered = input_reordered.reshape((input_tensor_data["shape"][2], input_tensor_data["shape"][3], input_tensor_data["shape"][0], input_tensor_data["shape"][1] // 64, 64))
        input_reordered = input_reordered.permute(3, 0, 1, 2, 4)
    input_int8 = input_reordered.to(torch.int8)
    input_start_addr = input_tensor_data["glb_base_address"]

    # INPUT SCALE
    # Shape is in format: (OC, IC / BLOCK_SIZE, Y, X)
    inputScale = read_tensor(base_path + inputScale_tensor_data["node"] + ".bin",
                             (inputScale_tensor_data["shape"][0], inputScale_tensor_data["shape"][1], inputScale_tensor_data["shape"][2], inputScale_tensor_data["shape"][3]))
    if zircon_input_padding_workaround:
        inputScale = F.pad(inputScale, pad=(0, zircon_input_padding_workaround_size, 0, zircon_input_padding_workaround_size)) # Pad X and Y dimensions with zeros
    # Re-order it so IC is the innermost dimension (Y, X, OC, IC / BLOCK_SIZE)
    inputScale_reordered = inputScale.permute(2, 3, 0, 1)
    if zircon_cgra_psum_workaround:
        inputScale_reordered = inputScale_reordered.permute(3, 0, 1, 2)
    inputScale_e8m0 = float_to_e8m0(inputScale_reordered)
    inputScale_start_addr = inputScale_tensor_data["glb_base_address"]

    # WEIGHT
    # Shape is in format: (OC, IC, FY, FX)
    weight = read_tensor(base_path + weight_tensor_data["node"] + ".bin",
                         (weight_tensor_data["shape"][0], weight_tensor_data["shape"][1], weight_tensor_data["shape"][2], weight_tensor_data["shape"][3]))
    if zircon_fx_fy_stride_workaround:
        weight = F.pad(weight, pad=(0, 2, 0, 2))
    # Re-order it so OC is the innermost dimension (FY, FX, IC, OC)
    weight_reordered = weight.permute(2, 3, 1, 0)
    if zircon_cgra_psum_workaround:
        weight_reordered = weight_reordered.reshape((weight_tensor_data["shape"][2], weight_tensor_data["shape"][3], weight_tensor_data["shape"][1] // 64, 64, weight_tensor_data["shape"][0]))
        weight_reordered = weight_reordered.permute(2, 0, 1, 3, 4)
    if k_dim_host_tiling:
        weight_reordered = weight_reordered.reshape((weight_tensor_data["shape"][2], weight_tensor_data["shape"][3], weight_tensor_data["shape"][1], num_k_host_tiling_kernels, weight_tensor_data["shape"][0] // num_k_host_tiling_kernels))
        weight_reordered = weight_reordered.permute(3, 0, 1, 2, 4)
        weight_reordered = weight_reordered[k_dim_host_tiling_idx]
    weight_int8 = weight_reordered.to(torch.int8)
    weight_start_addr = weight_tensor_data["glb_base_address"]

    # WEIGHT SCALE
    # Shape is in format: (OC, IC / BLOCK_SIZE, FY, FX)
    weightScale = read_tensor(base_path + weightScale_tensor_data["node"] + ".bin",
                              (weightScale_tensor_data["shape"][0], weightScale_tensor_data["shape"][1], weightScale_tensor_data["shape"][2], weightScale_tensor_data["shape"][3]))
    if zircon_fx_fy_stride_workaround:
        weightScale = F.pad(weightScale, pad=(0, 2, 0, 2))
    # Re-order it so OC is the innermost dimension (FY, FX, IC / BLOCK_SIZE, OC)
    weightScale_reordered = weightScale.permute(2, 3, 1, 0)
    if zircon_cgra_psum_workaround:
        weightScale_reordered = weightScale_reordered.permute(2, 0, 1, 3)
    if k_dim_host_tiling:
        weightScale_reordered = weightScale_reordered.reshape((weightScale_tensor_data["shape"][2], weightScale_tensor_data["shape"][3], weightScale_tensor_data["shape"][1], num_k_host_tiling_kernels, weightScale_tensor_data["shape"][0] // num_k_host_tiling_kernels))
        weightScale_reordered = weightScale_reordered.permute(3, 0, 1, 2, 4)
        weightScale_reordered = weightScale_reordered[k_dim_host_tiling_idx]
    weightScale_e8m0 = float_to_e8m0(weightScale_reordered)
    weightScale_start_addr = weightScale_tensor_data["glb_base_address"]

    # BIAS
    bias = read_tensor(base_path + bias_tensor_data["node"] + ".bin", (bias_tensor_data["shape"][0]))
    if zircon_cgra_psum_workaround and psum_idx != 0:
        # If doing psum workaround, bias is zero for all but the 0th kernel
        bias = torch.zeros((bias_tensor_data["shape"][0],), dtype=torch.float32)
    if k_dim_host_tiling:
        bias = bias.reshape((num_k_host_tiling_kernels, bias_tensor_data["shape"][0] // num_k_host_tiling_kernels))
        bias = bias[k_dim_host_tiling_idx]
    bias_bf16 = float32_to_bfloat16_bits(bias)
    bias_start_addr = bias_tensor_data["glb_base_address"]


    # RESIDUAL
    # Shape is in format: (OC, IC, Y, X)
    if has_residual:
        residual = read_tensor(base_path + residual_tensor_data["node"] + ".bin",
                               (residual_tensor_data["shape"][0], residual_tensor_data["shape"][1], residual_tensor_data["shape"][2], residual_tensor_data["shape"][3]))

        if zircon_fx_fy_stride_workaround:
            residual_tmp = torch.zeros(residual.size(0), residual.size(1), 2*residual.size(2), 2*residual.size(3), device=residual.device, dtype=residual.dtype)
            # Place original values at odd indices (1, 3, 5, ...) using slicing
            residual_tmp[:, :, 1::2, 1::2] = residual
            residual = residual_tmp

        # Re-order it so IC is the innermost dimension (Y, X, OC, IC)
        residual_reordered = residual.permute(2, 3, 0, 1)
        residual_bf16 = float32_to_bfloat16_bits(residual_reordered)
        residual_bf16_be = residual_bf16.byteswap().newbyteorder('>')

        if zircon_cgra_psum_workaround and (psum_idx == 0):
            residual_bf16_be.tofile(f'{h2h_dir}/hw_partial_sum_input_stencil.raw')
        # Write the residual_bf16_be to a raw file except for psum workaround middle kernels
        elif not(zircon_cgra_psum_workaround and psum_idx != (num_psums - 1)):
            residual_bf16_be.tofile(f'{h2h_dir}/hw_residual_input_stencil.raw')
        # Flatten residual_bf16 and convert to a python list
        residual_bf16 = residual_bf16.flatten().tolist()

    torch.set_printoptions(precision=10)

    # For psum_workoround, if not kernel 0, read prior kernel output from text file and convert to raw binary file
    if zircon_cgra_psum_workaround and (psum_idx != 0):
        hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_psum_reduction_fp/{model}-{layer}_gold/kernel_{psum_idx - 1}_output.txt'
        assert os.path.exists(hw_output_txt_path), f"The prior kernel output file {hw_output_txt_path} does not exist."
        # For the last psum, write to hw_residual_input_stencil.raw, otherwise write to hw_partial_sum_input_stencil.raw
        if psum_idx == (num_psums - 1):
            hw_output_raw_path = f'{h2h_dir}/hw_residual_input_stencil.raw'
        else:
            hw_output_raw_path = f'{h2h_dir}/hw_partial_sum_input_stencil.raw'
        hw_output_txt_to_raw(hw_output_txt_path, hw_output_raw_path)

    if debug_mode:
        debug_print_tensors(
            input, input_int8, bias, bias_bf16, inputScale, inputScale_e8m0,
            weightScale, weightScale_e8m0, weight)


    output_dir = f'/aha/voyager/compiled_collateral/{model}-{layer}/tensor_files/'

    # Write the tensors to hex files in tensor_files directory
    write_all_tensors_to_hex(
        input_int8, weight_int8, bias_bf16, inputScale_e8m0, weightScale_e8m0,
        output_dir,
        input_start_addr=input_start_addr,
        weight_start_addr=weight_start_addr,
        bias_start_addr=bias_start_addr,
        inputScale_start_addr=inputScale_start_addr,
        weightScale_start_addr=weightScale_start_addr,
        has_residual=has_residual,
        residual_bf16=residual_bf16 if has_residual else None
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Parse DNN layer tensors from binary files and convert them to hex files.')
    parser.add_argument('--model', type=str, required=True, help='Model name (e.g., resnet18)')
    parser.add_argument('--layer', type=str, required=True, help='Layer name (e.g., conv2d_mx_default_11)')
    parser.add_argument('--datatype', type=str, default='MXINT8', help='Data type of the tensors')
    parser.add_argument('--h2h_dir', type=str, required=True, default='/aha/Halide-to-Hardware/', help='Path to Halide-to-Hardware directory')
    parser.add_argument('--debug', action='store_true', help='Enable debug mode to print tensor values')

    args = parser.parse_args()

    parse_tensors(args.model, args.layer, args.datatype, args.h2h_dir, args.debug)