import math
import os
import struct
import numpy as np

import torch
import torch.nn.functional as F

import argparse
import json

# from custom_validation import do_custom_validation

# This file is used to parse the .bin tensor files generated by the voyager compiler. It extracts the required tensors, (input, weight, bias, inputScale, weightScale)
# converts them from float32 to int8, bfloat16, and e8m0 formats, tranposes them to the required layout in memory, allocates GLB memory for each tensor, and writes them to hex files
# consumable by the AHA flow.

ZIRCON_MU_IC0 = 64
ZIRCON_MU_OC0 = 32
ZIRCON_MU_WORD_NUM_BYTES = 32

def verify_bert_gelu():
    # Read input tensor
    input_path = "/aha/voyager/test/compiler/networks/bert/MXINT8/tensor_files/linear_mx_default_4.bin"
    input_shape = (128, 3072)
    input_tensor = read_tensor(input_path, input_shape)

    # Apply GELU on input_tensor using sigmoid approximation
    output_bf16_approx = torch.zeros_like(input_tensor, dtype=torch.bfloat16)
    for i in range(input_tensor.shape[0]):
        for j in range(input_tensor.shape[1]):
            x = input_tensor[i, j].item()
            sigmoid_approx = x * (1 / (1 + math.exp(-1.702 * x)))
            output_bf16_approx[i, j] = torch.tensor(sigmoid_approx, dtype=torch.bfloat16)

    # Convert output to float32 so can use float32_to_bfloat16_bits
    output_bf16_approx = output_bf16_approx.to(torch.float32)
    # output_bf16_approx = float32_to_bfloat16_bits(output_bf16_approx)
    # output_bf16_approx = output_bf16_approx.flatten().tolist()

    return output_bf16_approx, "bfloat16"

    # # Write output tensor to hex file
    # write_list_to_hex(output_bf16_approx, '/aha/voyager/gold_activation.txt', "", add_metadata=False)


def verify_llama_prefill_silu():
    print("Running custom validation for SiLU approximation on LLaMA prefill...")
    # Read input tensor
    input_path = "/aha/voyager/test/compiler/networks/llama_prefill/MXINT8/tensor_files/linear_mx_default_4.bin"
    input_shape = (512, 8192)
    input_tensor = read_tensor(input_path, input_shape)

    # Apply SiLU on input_tensor using sigmoid approximation
    output_bf16_approx = torch.zeros_like(input_tensor, dtype=torch.bfloat16)
    for i in range(input_tensor.shape[0]):
        for j in range(input_tensor.shape[1]):
            x = input_tensor[i, j].item()
            sigmoid_approx = x * (1 / (1 + math.exp(-1* x)))
            output_bf16_approx[i, j] = torch.tensor(sigmoid_approx, dtype=torch.bfloat16)

    # Convert output to float32 so can use float32_to_bfloat16_bits
    output_bf16_approx = output_bf16_approx.to(torch.float32)
    # output_bf16_approx = float32_to_bfloat16_bits(output_bf16_approx)
    # output_bf16_approx = output_bf16_approx.flatten().tolist()
    output_bf16_approx = output_bf16_approx.reshape(1, 512, 8192)
    return output_bf16_approx, "bfloat16"

    # # Write output tensor to hex file
    # write_list_to_hex(output_bf16_approx, '/aha/voyager/gold_activation.txt', "", add_metadata=False)


def verify_bert_tanh():
    # Read gold tensor
    gold_path = "/aha/voyager/test/compiler/networks/bert/MXINT8/tensor_files/tanh.bin"
    gold_shape = (1, 768)
    gold_tensor = read_tensor(gold_path, gold_shape)

    # gold_tensor_bf16 = float32_to_bfloat16_bits(gold_tensor)
    # gold_tensor_bf16 = gold_tensor_bf16.flatten().tolist()

    return gold_tensor, "bfloat16"

    # # Write output tensor to hex file
    # write_list_to_hex(gold_tensor_bf16, '/aha/voyager/gold_activation.txt', "", add_metadata=False)

def verify_resnet18_submodule():
    # Read gold tensor
    gold_path = "/aha/voyager/test/compiler/networks/resnet18/MXINT8/tensor_files/submodule_1.bin"
    gold_shape = (1, 12544, 64)
    gold_tensor = read_tensor(gold_path, gold_shape)

    # x_dim_host_tiling = "ZIRCON_GEMM_X_DIM_HOST_TILING" in os.environ and os.environ["ZIRCON_GEMM_X_DIM_HOST_TILING"] == "1"

    # if x_dim_host_tiling:
    #     if "X_DIM_HOST_TILING_SLICE_LENGTH" in os.environ:
    #         x_dim_host_tiling_slice_length = int(os.environ.get("X_DIM_HOST_TILING_SLICE_LENGTH"))

    #     if "X_DIM_HOST_TILING_SLICE_OFFSET" in os.environ:
    #         x_dim_host_tiling_slice_offset = int(os.environ.get("X_DIM_HOST_TILING_SLICE_OFFSET"))

    #     if "NUM_X_HOST_TILING_KERNELS" in os.environ:
    #         num_x_host_tiling_kernels = int(os.environ.get("NUM_X_HOST_TILING_KERNELS"))

    #     if "X_DIM_HOST_TILING_KERNEL_IDX" in os.environ:
    #         x_dim_host_tiling_kernel_idx = int(os.environ.get("X_DIM_HOST_TILING_KERNEL_IDX"))

    #     assert (x_dim_host_tiling_slice_length is not None and x_dim_host_tiling_slice_offset is not None) or (num_x_host_tiling_kernels is not None and x_dim_host_tiling_kernel_idx is not None), "Either X_DIM_HOST_TILING_SLICE_LENGTH and X_DIM_HOST_TILING_SLICE_OFFSET or NUM_X_HOST_TILING_KERNELS and X_DIM_HOST_TILING_KERNEL_IDX environment variables must be set for ZIRCON_GEMM_X_DIM_HOST_TILING"

    #     if len(gold_tensor.shape) == 3:
    #         if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
    #             gold_tensor = gold_tensor[:, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
    #         else:
    #             gold_tensor = gold_tensor.reshape((gold_tensor.shape[0], num_x_host_tiling_kernels, gold_tensor.shape[1] // num_x_host_tiling_kernels, gold_tensor.shape[2]))
    #             gold_tensor = gold_tensor.permute(1, 0, 2, 3)
    #             gold_tensor = gold_tensor[x_dim_host_tiling_kernel_idx]
    #     # Error out becuase it's not supported yet
    #     else:
    #         raise NotImplementedError("X dimension host tiling is not supported for non 3-D tensors yet.")

    # gold_tensor_bf16 = float32_to_bfloat16_bits(gold_tensor)
    # gold_tensor_bf16 = gold_tensor_bf16.flatten().tolist()

    return gold_tensor, "bfloat16"

    # # Write output tensor to hex file
    # write_list_to_hex(gold_tensor_bf16, '/aha/voyager/gold_activation.txt', "", add_metadata=False)

def verify_fakegemm_linear():
    # Read gold tensor
    gold_path = "/aha/voyager/test/compiler/networks/fakegemm/MXINT8/tensor_files/dequantize_default.bin"
    gold_shape = (3364, 32)
    gold_tensor = read_tensor(gold_path, gold_shape)

    # gold_tensor_bf16 = float32_to_bfloat16_bits(gold_tensor)
    # gold_tensor_bf16 = gold_tensor_bf16.flatten().tolist()

    return gold_tensor, "bfloat16"

    # # Write output tensor to hex file
    # write_list_to_hex(gold_tensor_bf16, '/aha/voyager/gold_activation.txt', "", add_metadata=False)

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser(description="Custom validation scripts for AHA Voyager flows.")
#     # Add model and layer args
#     parser.add_argument("--model", required=True, help="Model name (e.g., bert, resnet18)")
#     parser.add_argument("--layer", required=True, help="Layer name (e.g., linear_mx_default_4)")

#     args = parser.parse_args()
#     model = args.model
#     layer = args.layer

#     if model == "bert" and (layer == "linear_mx_default_4" or layer == "gelu"):
#         verify_bert_gelu()
#     elif model == "llama_prefill" and (layer == "linear_mx_default_4" or layer == "silu"):
#         verify_llama_prefill_silu()
#     elif model == "bert" and layer == "tanh":
#         verify_bert_tanh()
#     elif model == "fakegemm" and layer == "linear_default_1":
#         verify_fakegemm_linear()
#     elif model == "resnet18" and layer == "submodule":
#         verify_resnet18_submodule()
#     else:
#         raise NotImplementedError(f"No custom validation script for model {model} layer {layer}")


def do_custom_validation(model, layer):
    if model == "bert" and (layer == "linear_mx_default_4" or layer == "gelu"):
        return verify_bert_gelu()
    elif model == "llama_prefill" and (layer == "linear_mx_default_4" or layer == "silu"):
        return verify_llama_prefill_silu()
    elif model == "bert" and layer == "tanh":
        return verify_bert_tanh()
    elif model == "fakegemm" and layer == "linear_default_1":
        return verify_fakegemm_linear()
    elif model == "resnet18" and layer == "submodule":
        return verify_resnet18_submodule()
    else:
        raise NotImplementedError(f"No custom validation script for model {model} layer {layer}")


def read_tensor(filename, tensor_shape):
    with open(filename, 'rb') as f:
        file_content = f.read()

    num_elements = len(file_content) // struct.calcsize('f')
    print(f"INFO: Read {num_elements} elements from binary file {filename}")
    unpacked_data = struct.unpack(f'{num_elements}f', file_content)

    tensor = torch.tensor(unpacked_data).reshape(tensor_shape)
    return tensor

def get_scale_from_bin(filename):
    with open(filename, 'rb') as f:
        file_content = f.read()

        num_elements = len(file_content) // struct.calcsize('f')
        print(f"INFO: Read {num_elements} elements from binary file {filename}")
        unpacked_data = struct.unpack(f'{num_elements}f', file_content)

        tensor = torch.tensor(unpacked_data).reshape(1,)
        return tensor[0].item()

def float_to_e8m0(x):
    # Assume input is a float32 tensor
    x = x.cpu().numpy().astype(np.float32)
    bits = np.frombuffer(x.tobytes(), dtype=np.uint32)
    e8m0 = ((bits >> 23) & 0xFF)  # extract exponent only
    return e8m0


def float32_to_bfloat16_bits(x):
    # Step 1: Move to CPU and convert to NumPy float32
    np_fp32 = x.cpu().numpy().astype(np.float32)

    # Step 2: View as uint32
    np_uint32 = np_fp32.view(np.uint32)

    # Step 3: Extract top 16 bits (bfloat16 format)
    np_bf16_uint16 = (np_uint32 >> 16).astype(np.uint16)

    return np_bf16_uint16


def write_list_to_hex(list, filename, start_addr=0, add_metadata=True, hex_width=4):
    #Write the entire tensor in hex format to a new file
    with open(filename, 'w') as output_file:
            if add_metadata:
                output_file.write(f"TENSOR_EXISTS: 1\n")
                output_file.write(f"SIZE: {len(list)}\n")
                output_file.write(f"START_ADDR: {start_addr}\n")
            for idx in range(len(list)):
                value = list[idx]
                if hex_width == 2:
                    output_file.write(str(f"{value:02x}"))
                    if idx != len(list) - 1:
                        output_file.write("\n")
                elif hex_width == 4:
                    output_file.write(str(f"{value:04x}"))
                    if idx != len(list) - 1:
                        output_file.write("\n")
                else:
                    raise ValueError(f"Unsupported hex width {hex_width} for writing hex file.")

def debug_print_tensors(input, input_int8, bias_bf16, inputScale_e8m0, weightScale_e8m0):
        # Print first 10 elements and max value
        print("First 10 elements of the input tensor:", input.flatten()[:10])
        print("Max value of the input tensor:", torch.max(input))

        print("First 10 elements of the input INT8 tensor:", input_int8.flatten()[:10])
        print("Max value of the input INT8 tensor:", torch.max(input_int8))

        print("First 10 elements of the bias bFloat16 tensor:", bias_bf16.flatten()[:10])

        print("First 10 elements of the inputScale e8m0 tensor:", inputScale_e8m0.flatten()[:10])

        print("First 10 elements of the weightScale e8m0 tensor:", weightScale_e8m0.flatten()[:10])

        print("Shape of the bytes object:", len(input_int8.numpy().tobytes()))

def write_all_in_tensors_to_hex(
        output_dir,
        input_int8=None, input_bf16_cgra=None, weight_int8=None, weight_bf16_cgra=None, bias_bf16=None, bias_bf16_cgra=None, inputScale_e8m0=None, inputScale_e8m0_packed_cgra=None, weightScale_e8m0=None, residual_bf16=None,
        input_start_addr=0, weight_start_addr=0, bias_start_addr=0, inputScale_start_addr=0, weightScale_start_addr=0,
        residual_start_addr="set by io_placement", input_bf16_cgra_start_addr="set by io_placement", weight_bf16_cgra_start_addr="set by io_placement", bias_bf16_cgra_start_addr="set by io_placement", inputScale_e8m0_packed_cgra_start_addr="set by io_placement"
    ):

        if input_int8 is not None:
            write_list_to_hex(input_int8.numpy().tobytes(), output_dir + 'input_hex.txt', input_start_addr)
        else:
            with open(output_dir + 'input_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if input_bf16_cgra is not None:
            write_list_to_hex(input_bf16_cgra, output_dir + 'input_bf16_cgra_hex.txt', input_bf16_cgra_start_addr)
        else:
            with open(output_dir + 'input_bf16_cgra_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if inputScale_e8m0_packed_cgra is not None:
            write_list_to_hex(inputScale_e8m0_packed_cgra, output_dir + 'inputScale_e8m0_packed_cgra_hex.txt', inputScale_e8m0_packed_cgra_start_addr)
        else:
            with open(output_dir + 'inputScale_e8m0_packed_cgra_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if weight_bf16_cgra is not None:
            write_list_to_hex(weight_bf16_cgra, output_dir + 'weight_bf16_cgra_hex.txt', weight_bf16_cgra_start_addr)
        else:
            with open(output_dir + 'weight_bf16_cgra_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if weight_int8 is not None:
            write_list_to_hex(weight_int8.numpy().tobytes(), output_dir + 'weight_hex.txt', weight_start_addr)
        else:
            with open(output_dir + 'weight_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if bias_bf16 is not None:
            write_list_to_hex(bias_bf16, output_dir + 'bias_hex.txt', bias_start_addr)
        else:
            with open(output_dir + 'bias_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if bias_bf16_cgra is not None:
            write_list_to_hex(bias_bf16_cgra, output_dir + 'bias_bf16_cgra_hex.txt', bias_bf16_cgra_start_addr)
        else:
            with open(output_dir + 'bias_bf16_cgra_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if inputScale_e8m0 is not None:
            write_list_to_hex(inputScale_e8m0, output_dir + 'inputScale_hex.txt', inputScale_start_addr)
        else:
            with open(output_dir + 'inputScale_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if weightScale_e8m0 is not None:
            write_list_to_hex(weightScale_e8m0, output_dir + 'weightScale_hex.txt', weightScale_start_addr)
        else:
            with open(output_dir + 'weightScale_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")

        if residual_bf16 is not None:
            write_list_to_hex(residual_bf16, output_dir + 'residual_hex.txt', residual_start_addr)
        else:
            with open(output_dir + 'residual_hex.txt', 'w') as f:
                f.write("TENSOR_EXISTS: 0\n")


def trim_channels_if_needed(tensor):
    GOLD_CHANNEL_TRIMMING_WORKAROUND = "GOLD_CHANNEL_TRIMMING_WORKAROUND" in os.environ and os.environ["GOLD_CHANNEL_TRIMMING_WORKAROUND"] == "1"
    if GOLD_CHANNEL_TRIMMING_WORKAROUND:
        assert "GOLD_CHANNEL_TRIMMING_WORKAROUND_NUM_KERNELS" in os.environ, "GOLD_CHANNEL_TRIMMING_WORKAROUND_NUM_KERNELS environment variable must be set for GOLD_CHANNEL_TRIMMING_WORKAROUND"
        gold_channel_trimming_workaround_num_kernels = int(os.environ["GOLD_CHANNEL_TRIMMING_WORKAROUND_NUM_KERNELS"])
        assert "GOLD_CHANNEL_TRIMMING_WORKAROUND_KERNEL_IDX" in os.environ, "GOLD_CHANNEL_TRIMMING_WORKAROUND_KERNEL_IDX environment variable must be set for GOLD_CHANNEL_TRIMMING_WORKAROUND"
        gold_channel_trimming_workaround_kernel_idx = int(os.environ["GOLD_CHANNEL_TRIMMING_WORKAROUND_KERNEL_IDX"])

        tensor = tensor.reshape((-1, gold_channel_trimming_workaround_num_kernels, ZIRCON_MU_OC0 // gold_channel_trimming_workaround_num_kernels))
        tensor = tensor[:, gold_channel_trimming_workaround_kernel_idx, :].reshape(-1)
    return tensor

# For writing partial sum output from a prior kernel to raw binary file
def hw_output_txt_to_raw(input_txt_path, output_raw_path):
    # Read the file content
    with open(input_txt_path, 'r') as f:
        hex_values = f.read().split()

    # Convert hex strings to unsigned 16-bit integers
    uint16_array = np.array([int(h, 16) for h in hex_values], dtype=np.uint16)

    # Swap byte order
    uint16_array_be = uint16_array.byteswap().newbyteorder('>')

    # Trim channels if needed
    uint16_array_be = trim_channels_if_needed(uint16_array_be)

    # Save to raw binary file
    uint16_array_be.tofile(output_raw_path)


def parse_zircon_workarounds():
    # Workaround needed to avoid Zircon MU bug on Resnet downsample layers and in GEMM layers
    zircon_inner_loop_reduction_workaround = "ZIRCON_INNER_LOOP_REDUCTION_WORKAROUND" in os.environ and os.environ["ZIRCON_INNER_LOOP_REDUCTION_WORKAROUND"] == "1"

    # Workarounds to avoid Zircon MU bug on Resnet downsample layers
    zircon_fx_fy_stride_workaround = "ZIRCON_FX_FY_STRIDE_WORKAROUND" in os.environ and os.environ["ZIRCON_FX_FY_STRIDE_WORKAROUND"] == "1"
    zircon_cgra_psum_workaround = "ZIRCON_CGRA_PSUM_WORKAROUND" in os.environ and os.environ["ZIRCON_CGRA_PSUM_WORKAROUND"] == "1"
    zircon_outer_reduction_tiling_workaround = "ZIRCON_OUTER_REDUCTION_TILING_WORKAROUND" in os.environ and os.environ["ZIRCON_OUTER_REDUCTION_TILING_WORKAROUND"] == "1"
    zircon_gemm_reduction_tiling_workaround = "ZIRCON_GEMM_REDUCTION_TILING_WORKAROUND" in os.environ and os.environ["ZIRCON_GEMM_REDUCTION_TILING_WORKAROUND"] == "1"
    psum_idx = 0
    num_psums = 1
    intermediate_gold_idx = 0
    if zircon_cgra_psum_workaround or zircon_outer_reduction_tiling_workaround or zircon_gemm_reduction_tiling_workaround:
        assert "PSUM_IDX" in os.environ, "PSUM_IDX environment variable must be set for ZIRCON_CGRA_PSUM_WORKAROUND or ZIRCON_OUTER_REDUCTION_TILING_WORKAROUND or ZIRCON_GEMM_REDUCTION_TILING_WORKAROUND"
        assert "NUM_PSUMS" in os.environ, "NUM_PSUMS environment variable must be set for ZIRCON_CGRA_PSUM_WORKAROUND or ZIRCON_OUTER_REDUCTION_TILING_WORKAROUND or ZIRCON_GEMM_REDUCTION_TILING_WORKAROUND"
        psum_idx = int(os.environ["PSUM_IDX"])
        num_psums = int(os.environ["NUM_PSUMS"])

        intermediate_gold_idx = os.environ.get("INTERMEDIATE_GOLD_IDX", None)
        if intermediate_gold_idx is None:
            intermediate_gold_idx = psum_idx
        else:
            intermediate_gold_idx = int(intermediate_gold_idx)
    # if zircon_outer_reduction_tiling_workaround:
    #     assert "INTERMEDIATE_GOLD_DIR" in os.environ, "INTERMEDIATE_GOLD_DIR environment variable must be set for ZIRCON_OUTER_REDUCTION_TILING_WORKAROUND"
    #     intermediate_gold_dir = os.environ["INTERMEDIATE_GOLD_DIR"]

    # Input padding workaround for Zircon MU inability to handle some layer shapes
    zircon_input_act_padding_workaround = "ZIRCON_INPUT_ACT_PADDING_WORKAROUND" in os.environ and os.environ["ZIRCON_INPUT_ACT_PADDING_WORKAROUND"] == "1"
    zircon_input_act_padding_workaround_size = 0
    zircon_input_act_padding_workaround_stride = 1
    if zircon_input_act_padding_workaround:
        assert "ZIRCON_INPUT_ACT_PADDING_WORKAROUND_SIZE" in os.environ, "ZIRCON_INPUT_ACT_PADDING_WORKAROUND_SIZE environment variable must be set for ZIRCON_INPUT_ACT_PADDING_WORKAROUND"
        zircon_input_act_padding_workaround_size = int(os.environ.get("ZIRCON_INPUT_ACT_PADDING_WORKAROUND_SIZE"))
        assert "ZIRCON_INPUT_ACT_PADDING_WORKAROUND_STRIDE" in os.environ, "ZIRCON_INPUT_ACT_PADDING_WORKAROUND_STRIDE environment variable must be set for ZIRCON_INPUT_ACT_PADDING_WORKAROUND"
        zircon_input_act_padding_workaround_stride = int(os.environ.get("ZIRCON_INPUT_ACT_PADDING_WORKAROUND_STRIDE"))

    # K dimension host tiling: used in resnet18 conv5 in Zircon
    k_dim_host_tiling = "K_DIM_HOST_TILING" in os.environ and os.environ["K_DIM_HOST_TILING"] == "1"
    num_k_host_tiling_kernels = 1
    k_dim_host_tiling_idx = 0
    k_dim_host_tiling_pre_slicing = False
    k_dim_host_tiling_pre_slicing_slice_offset = 0
    k_dim_host_tiling_pre_slicing_slice_length = None
    if k_dim_host_tiling:
        assert "NUM_K_HOST_TILING_KERNELS" in os.environ, "NUM_K_HOST_TILING_KERNELS environment variable must be set for K_DIM_HOST_TILING"
        assert "K_DIM_HOST_TILING_IDX" in os.environ, "K_DIM_HOST_TILING_IDX environment variable must be set for K_DIM_HOST_TILING"
        num_k_host_tiling_kernels = int(os.environ.get("NUM_K_HOST_TILING_KERNELS"))
        k_dim_host_tiling_idx = int(os.environ.get("K_DIM_HOST_TILING_IDX"))

        k_dim_host_tiling_pre_slicing = "K_DIM_HOST_TILING_PRE_SLICING" in os.environ and os.environ["K_DIM_HOST_TILING_PRE_SLICING"] == "1"
        if k_dim_host_tiling_pre_slicing:
            assert "K_DIM_HOST_TILING_PRE_SLICING_SLICE_OFFSET" in os.environ, "K_DIM_HOST_TILING_PRE_SLICING_SLICE_OFFSET environment variable must be set for K_DIM_HOST_TILING_PRE_SLICING"
            assert "K_DIM_HOST_TILING_PRE_SLICING_SLICE_LENGTH" in os.environ, "K_DIM_HOST_TILING_PRE_SLICING_SLICE_LENGTH environment variable must be set for K_DIM_HOST_TILING_PRE_SLICING"
            k_dim_host_tiling_pre_slicing_slice_offset = int(os.environ.get("K_DIM_HOST_TILING_PRE_SLICING_SLICE_OFFSET"))
            k_dim_host_tiling_pre_slicing_slice_length = int(os.environ.get("K_DIM_HOST_TILING_PRE_SLICING_SLICE_LENGTH"))


    # Non uniform slicing
    non_uniform_slicing = "NON_UNIFORM_SLICING" in os.environ and os.environ["NON_UNIFORM_SLICING"] == "1"
    non_uniform_slice_idx = 0
    if non_uniform_slicing:
        non_uniform_slice_idx = int(os.environ.get("NON_UNIFORM_SLICE_IDX", 1))

    # X dim host tiling for GEMM
    x_dim_host_tiling = "ZIRCON_GEMM_X_DIM_HOST_TILING" in os.environ and os.environ["ZIRCON_GEMM_X_DIM_HOST_TILING"] == "1"
    x_dim_host_tiling_slice_offset = None
    x_dim_host_tiling_slice_length = None
    num_x_host_tiling_kernels = None
    x_dim_host_tiling_kernel_idx = None

    if x_dim_host_tiling:
        if "X_DIM_HOST_TILING_SLICE_LENGTH" in os.environ:
            x_dim_host_tiling_slice_length = int(os.environ.get("X_DIM_HOST_TILING_SLICE_LENGTH"))


        if "X_DIM_HOST_TILING_SLICE_OFFSET" in os.environ:
            x_dim_host_tiling_slice_offset = int(os.environ.get("X_DIM_HOST_TILING_SLICE_OFFSET"))

        if "NUM_X_HOST_TILING_KERNELS" in os.environ:
            num_x_host_tiling_kernels = int(os.environ.get("NUM_X_HOST_TILING_KERNELS"))

        if "X_DIM_HOST_TILING_IDX" in os.environ:
            x_dim_host_tiling_kernel_idx = int(os.environ.get("X_DIM_HOST_TILING_IDX"))

        assert (x_dim_host_tiling_slice_length is not None and x_dim_host_tiling_slice_offset is not None) or (num_x_host_tiling_kernels is not None and x_dim_host_tiling_kernel_idx is not None), "Either X_DIM_HOST_TILING_SLICE_LENGTH and X_DIM_HOST_TILING_SLICE_OFFSET or NUM_X_HOST_TILING_KERNELS and X_DIM_HOST_TILING_IDX environment variables must be set for ZIRCON_GEMM_X_DIM_HOST_TILING"

    # I/O dimension 0 host tiling
    io_innermost_dim_tiling = "IO_INNERMOST_DIM_TILING" in os.environ and os.environ["IO_INNERMOST_DIM_TILING"] == "1"
    output_tensor_io_innermost_dim_tiling = False
    num_io_innermost_dim_tiling_kernels = 0
    io_innermost_dim_tiling_idx = 0
    if io_innermost_dim_tiling:
        output_tensor_io_innermost_dim_tiling = "OUTPUT_TENSOR_IO_INNERMOST_DIM_TILING" in os.environ and os.environ["OUTPUT_TENSOR_IO_INNERMOST_DIM_TILING"] == "1"
        assert "NUM_IO_INNERMOST_DIM_TILING_KERNELS" in os.environ, "NUM_IO_INNERMOST_DIM_TILING_KERNELS environment variable must be set for io_innermost_dim_tiling"
        assert "IO_INNERMOST_DIM_TILING_IDX" in os.environ, "IO_INNERMOST_DIM_TILING_IDX environment variable must be set for io_innermost_dim_tiling"
        num_io_innermost_dim_tiling_kernels = int(os.environ["NUM_IO_INNERMOST_DIM_TILING_KERNELS"])
        io_innermost_dim_tiling_idx = int(os.environ["IO_INNERMOST_DIM_TILING_IDX"])


    # I/O dimension 1 host tiling
    io_dim1_tiling = "IO_DIM1_TILING" in os.environ and os.environ["IO_DIM1_TILING"] == "1"
    output_tensor_io_dim1_tiling = False
    num_io_dim1_tiling_kernels = 0
    io_dim1_tiling_idx = 0
    if io_dim1_tiling:
        output_tensor_io_dim1_tiling = "OUTPUT_TENSOR_IO_DIM1_TILING" in os.environ and os.environ["OUTPUT_TENSOR_IO_DIM1_TILING"] == "1"
        assert "NUM_IO_DIM1_TILING_KERNELS" in os.environ, "NUM_IO_DIM1_TILING_KERNELS environment variable must be set for io_dim1_tiling"
        assert "IO_DIM1_TILING_IDX" in os.environ, "IO_DIM1_TILING_IDX environment variable must be set for io_dim1_tiling"
        num_io_dim1_tiling_kernels = int(os.environ["NUM_IO_DIM1_TILING_KERNELS"])
        io_dim1_tiling_idx = int(os.environ["IO_DIM1_TILING_IDX"])

    # Padding OC dimension for fully connected layers
    pad_oc = "PAD_OC" in os.environ and os.environ["PAD_OC"] == "1"

    output_tensor_k_dim_tiling = "OUTPUT_TENSOR_K_DIM_TILING" in os.environ and os.environ["OUTPUT_TENSOR_K_DIM_TILING"] == "1"


    if zircon_inner_loop_reduction_workaround:
        print("\033[93mINFO: Zircon inner loop reduction workaround enabled. The outer channel loop is moved to the inner level. This should only be used to avoid the Zircon MU bug on Resnet downsample layers and in GEMM layers.\033[0m")

    if zircon_cgra_psum_workaround:
        print(f"\033[93mINFO: Zircon CGRA PSUM workaround enabled to avoid MU bug on downsample layers. Using PSUM index {psum_idx}. There are {num_psums} total PSUMs.\033[0m")

    if zircon_outer_reduction_tiling_workaround:
        print(f"\033[93mINFO: Zircon outer channel tiling workaround enabled to avoid MU bug on downsample layers. Using PSUM index {psum_idx}. There are {num_psums} total PSUMs.\033[0m")

    if zircon_gemm_reduction_tiling_workaround:
        print(f"\033[93mINFO: Zircon GEMM reduction tiling workaround enabled to avoid MU bug in some GEMM layers. Using PSUM index {psum_idx}. There are {num_psums} total PSUMs.\033[0m")

    if zircon_fx_fy_stride_workaround:
        print("\033[93mINFO: Zircon FX, FY stride workaround enabled to avoid MU bug on downsample layers.\033[0m")

    if zircon_input_act_padding_workaround:
        print(f"\033[93mINFO: Zircon input padding workaround enabled. Input image will be padded with +{zircon_input_act_padding_workaround_size}. The stride is {zircon_input_act_padding_workaround_stride}.\033[0m")

    if k_dim_host_tiling:
        print(f"\033[93mINFO: K dimension host tiling enabled. Using {num_k_host_tiling_kernels} kernels with index {k_dim_host_tiling_idx}.\033[0m")
        if output_tensor_k_dim_tiling:
            print(f"\033[93mINFO: Output tensor K dimension tiling enabled. Output tensor will be tiled along the K dimension for the host tiled kernels.\033[0m")

    if k_dim_host_tiling_pre_slicing:
        print(f"\033[93mINFO: K dimension host tiling pre-slicing enabled. The input tensor will be sliced along the K dimension with slice offset {k_dim_host_tiling_pre_slicing_slice_offset} and slice length {k_dim_host_tiling_pre_slicing_slice_length} before being fed into the kernel.\033[0m")


    if non_uniform_slicing:
        print(f"\033[93mINFO: Non-uniform slicing enabled. Using slice index {non_uniform_slice_idx} for this kernel.\033[0m")

    if x_dim_host_tiling:
        if x_dim_host_tiling_slice_length is not None and x_dim_host_tiling_slice_offset is not None:
            print(f"\033[93mINFO: X dimension host tiling enabled for GEMM. Using slice offset {x_dim_host_tiling_slice_offset} and slice length {x_dim_host_tiling_slice_length} along the x dimension.\033[0m")
        else:
            print(f"\033[93mINFO: X dimension host tiling enabled for GEMM. Using {num_x_host_tiling_kernels} kernels with index {x_dim_host_tiling_kernel_idx} along the x dimension.\033[0m")

    if pad_oc:
        print("\033[93mINFO: OC dimension padding is turned on.\033[0m")

    if io_innermost_dim_tiling:
        print(f"\033[93mINFO: I/O dimension 0 host tiling enabled. Using {num_io_innermost_dim_tiling_kernels} kernels with index {io_innermost_dim_tiling_idx}. Output tensor I/O dim0 tiling: {output_tensor_io_innermost_dim_tiling}.\033[0m")


    if io_dim1_tiling:
        print(f"\033[93mINFO: I/O dimension 1 host tiling enabled. Using {num_io_dim1_tiling_kernels} kernels with index {io_dim1_tiling_idx}. Output tensor I/O dim1 tiling: {output_tensor_io_dim1_tiling}.\033[0m")


    return {
        "zircon_fx_fy_stride_workaround": zircon_fx_fy_stride_workaround,
        "zircon_cgra_psum_workaround": zircon_cgra_psum_workaround,
        "zircon_outer_reduction_tiling_workaround": zircon_outer_reduction_tiling_workaround,
        "zircon_gemm_reduction_tiling_workaround": zircon_gemm_reduction_tiling_workaround,
        # "intermediate_gold_dir": intermediate_gold_dir,
        "psum_idx": psum_idx,
        "intermediate_gold_idx": intermediate_gold_idx,
        "num_psums": num_psums,
        "zircon_input_act_padding_workaround": zircon_input_act_padding_workaround,
        "zircon_input_act_padding_workaround_size": zircon_input_act_padding_workaround_size,
        "zircon_input_act_padding_workaround_stride": zircon_input_act_padding_workaround_stride,
        "k_dim_host_tiling": k_dim_host_tiling,
        "num_k_host_tiling_kernels": num_k_host_tiling_kernels,
        "k_dim_host_tiling_idx": k_dim_host_tiling_idx,
        "k_dim_host_tiling_pre_slicing": k_dim_host_tiling_pre_slicing,
        "k_dim_host_tiling_pre_slicing_slice_offset": k_dim_host_tiling_pre_slicing_slice_offset,
        "k_dim_host_tiling_pre_slicing_slice_length": k_dim_host_tiling_pre_slicing_slice_length,
        "non_uniform_slicing": non_uniform_slicing,
        "non_uniform_slice_idx": non_uniform_slice_idx,
        "x_dim_host_tiling": x_dim_host_tiling,
        "x_dim_host_tiling_slice_offset": x_dim_host_tiling_slice_offset,
        "x_dim_host_tiling_slice_length": x_dim_host_tiling_slice_length,
        "num_x_host_tiling_kernels": num_x_host_tiling_kernels,
        "x_dim_host_tiling_idx": x_dim_host_tiling_kernel_idx,
        "pad_oc": pad_oc,
        "io_innermost_dim_tiling": io_innermost_dim_tiling,
        "num_io_innermost_dim_tiling_kernels": num_io_innermost_dim_tiling_kernels,
        "io_innermost_dim_tiling_idx": io_innermost_dim_tiling_idx,
        "output_tensor_io_innermost_dim_tiling": output_tensor_io_innermost_dim_tiling,
        "output_tensor_k_dim_tiling": output_tensor_k_dim_tiling,
        "io_dim1_tiling": io_dim1_tiling,
        "num_io_dim1_tiling_kernels": num_io_dim1_tiling_kernels,
        "io_dim1_tiling_idx": io_dim1_tiling_idx,
        "output_tensor_io_dim1_tiling": output_tensor_io_dim1_tiling
    }


def parse_input(base_path, input_tensor_data, zircon_workarounds):
    # For conv2d, shape is in format: (B, Y, X, IC)
    input = read_tensor(base_path + input_tensor_data["node"] + ".bin", tuple(input_tensor_data["shape"]))
    if zircon_workarounds["zircon_input_act_padding_workaround"]:
        input = input.permute(0, 3, 1, 2)  # Re-order to (B, IC, Y, X)
        pad_dim = zircon_workarounds["zircon_input_act_padding_workaround_size"] * zircon_workarounds["zircon_input_act_padding_workaround_stride"]
        input = F.pad(input, pad=(0, pad_dim, 0, pad_dim)) # Pad X and Y dimensions with zeros
        input = input.permute(0, 2, 3, 1)  # Re-order back to (B, Y, X, IC)
    if zircon_workarounds["zircon_cgra_psum_workaround"] or zircon_workarounds["zircon_outer_reduction_tiling_workaround"]:
        input = input.reshape((input.shape[0], input.shape[1], input.shape[2], input.shape[3] // ZIRCON_MU_IC0, ZIRCON_MU_IC0))
        input = input.permute(3, 0, 1, 2, 4)
    if zircon_workarounds["zircon_gemm_reduction_tiling_workaround"]:
        num_psums = zircon_workarounds["num_psums"]
        psum_idx = zircon_workarounds["psum_idx"]
        if len(input.shape) == 3:
            # Tile along the reduction dimension, which is the innermost dimension for input tensor
            input = input.reshape((input.shape[0], input.shape[1], num_psums, input.shape[2] // num_psums))
            input = input.permute(2, 0, 1, 3)
            input = input[psum_idx]
        else:
            raise NotImplementedError("Zircon GEMM reduction tiling workaround is only supported for 3-D (GEMM) input tensors currently.")
    # TODO: May need to add this for residual as well
    if zircon_workarounds["x_dim_host_tiling"]:
        x_dim_host_tiling_slice_offset = zircon_workarounds["x_dim_host_tiling_slice_offset"]
        x_dim_host_tiling_slice_length = zircon_workarounds["x_dim_host_tiling_slice_length"]
        num_x_host_tiling_kernels = zircon_workarounds["num_x_host_tiling_kernels"]
        x_dim_host_tiling_kernel_idx = zircon_workarounds["x_dim_host_tiling_idx"]
        if len(input.shape) == 3:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                input = input[:, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                input = input.reshape((input.shape[0], num_x_host_tiling_kernels, input.shape[1] // num_x_host_tiling_kernels, input.shape[2]))
                input = input.permute(1, 0, 2, 3)
                input = input[x_dim_host_tiling_kernel_idx]
        # Error out becuase it's not supported yet
        else:
            raise NotImplementedError("X dimension host tiling is not supported for non 3-D (conv1 im2col) tensors yet.")
    input_int8 = input.to(torch.int8)

    return input_int8


def parse_inputScale(base_path, inputScale_tensor_data, zircon_workarounds):
    # For conv2d, shape is in format: (B, Y, X, IC / BLOCK_SIZE)
    inputScale = read_tensor(base_path + inputScale_tensor_data["node"] + ".bin", tuple(inputScale_tensor_data["shape"]))
    if zircon_workarounds["zircon_input_act_padding_workaround"]:
        inputScale = inputScale.permute(0, 3, 1, 2)  # Re-order to (B, IC / BLOCK_SIZE, Y, X)
        pad_dim = zircon_workarounds["zircon_input_act_padding_workaround_size"] * zircon_workarounds["zircon_input_act_padding_workaround_stride"]
        inputScale = F.pad(inputScale, pad=(0, pad_dim, 0, pad_dim)) # Pad X and Y dimensions with zeros
        inputScale = inputScale.permute(0, 2, 3, 1)  # Re-order back to (B, Y, X, IC / BLOCK_SIZE)
    if zircon_workarounds["zircon_cgra_psum_workaround"] or zircon_workarounds["zircon_outer_reduction_tiling_workaround"]:
        inputScale = inputScale.permute(3, 0, 1, 2)

    if zircon_workarounds["zircon_gemm_reduction_tiling_workaround"]:
        num_psums = zircon_workarounds["num_psums"]
        psum_idx = zircon_workarounds["psum_idx"]
        if len(inputScale.shape) == 3:
            # Tile along the reduction dimension, which is the innermost dimension for inputScale tensor
            inputScale = inputScale.reshape((inputScale.shape[0], inputScale.shape[1], num_psums, inputScale.shape[2] // num_psums))
            inputScale = inputScale.permute(2, 0, 1, 3)
            inputScale = inputScale[psum_idx]
        else:
            raise NotImplementedError("Zircon GEMM reduction tiling workaround is only supported for 3-D (GEMM) inputScale tensors currently.")
    if zircon_workarounds["x_dim_host_tiling"]:
        x_dim_host_tiling_slice_offset = zircon_workarounds["x_dim_host_tiling_slice_offset"]
        x_dim_host_tiling_slice_length = zircon_workarounds["x_dim_host_tiling_slice_length"]
        num_x_host_tiling_kernels = zircon_workarounds["num_x_host_tiling_kernels"]
        x_dim_host_tiling_kernel_idx = zircon_workarounds["x_dim_host_tiling_idx"]
        if len(inputScale.shape) == 3:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                inputScale = inputScale[:, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                inputScale = inputScale.reshape((inputScale.shape[0], num_x_host_tiling_kernels, inputScale.shape[1] // num_x_host_tiling_kernels, inputScale.shape[2]))
                inputScale = inputScale.permute(1, 0, 2, 3)
                inputScale = inputScale[x_dim_host_tiling_kernel_idx]
        # Error out becuase it's not supported yet
        else:
            raise NotImplementedError("X dimension host tiling is not supported for non 3-D (conv1 im2col) tensors yet.")
    inputScale_e8m0 = float_to_e8m0(inputScale)

    return inputScale_e8m0

def parse_weight(base_path, weight_tensor_data, zircon_workarounds):
     # For conv2d, shape is in format: (FY, FX, IC, OC)
    weight = read_tensor(base_path + weight_tensor_data["node"] + ".bin", tuple(weight_tensor_data["shape"]))
    if zircon_workarounds["zircon_fx_fy_stride_workaround"]:
        weight = weight.permute(2, 3, 0, 1)  # Re-order to (IC, OC, FY, FX)
        weight = F.pad(weight, pad=(0, 2, 0, 2))
        weight = weight.permute(2, 3, 0, 1)  # Re-order back to (FY, FX, IC, OC)
    if zircon_workarounds["zircon_cgra_psum_workaround"] or zircon_workarounds["zircon_outer_reduction_tiling_workaround"]:
        weight = weight.reshape((weight.shape[0], weight.shape[1], weight.shape[2] // ZIRCON_MU_IC0, ZIRCON_MU_IC0, weight.shape[3]))
        weight = weight.permute(2, 0, 1, 3, 4)
    if zircon_workarounds["k_dim_host_tiling"]:
        num_k_host_tiling_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
        k_dim_host_tiling_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        if len(weight.shape) == 2:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                weight = weight[:, slice_offset:slice_offset + slice_length]
            weight = weight.reshape((weight.shape[0], num_k_host_tiling_kernels, weight.shape[1] // num_k_host_tiling_kernels))
            weight = weight.permute(1, 0, 2)
        elif len(weight.shape) == 4:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                weight = weight[:, :, :, slice_offset:slice_offset + slice_length]
            weight = weight.reshape((weight.shape[0], weight.shape[1], weight.shape[2], num_k_host_tiling_kernels, weight.shape[3] // num_k_host_tiling_kernels))
            weight = weight.permute(3, 0, 1, 2, 4)
        else:
            raise NotImplementedError("K dimension host tiling is only supported for 2-D (GEMM) and 4-D (conv2d) weight tensors currently.")
        weight = weight[k_dim_host_tiling_idx]

    if zircon_workarounds["zircon_gemm_reduction_tiling_workaround"]:
        num_psums = zircon_workarounds["num_psums"]
        psum_idx = zircon_workarounds["psum_idx"]
        if len(weight.shape) == 2:
            # Tile along the reduction dimension, which is the outermost dimension for weight tensor
            weight = weight.reshape((num_psums, weight.shape[0] // num_psums, weight.shape[1]))
            weight = weight[psum_idx]
        else:
            raise NotImplementedError("Zircon GEMM reduction tiling workaround is only supported for 2-D (GEMM) weight tensors currently.")
    weight_int8 = weight.to(torch.int8)

    return weight_int8

def parse_weightScale(base_path, weightScale_tensor_data, zircon_workarounds):
     # For conv2d, shape is in format: (FY, FX, IC / BLOCK_SIZE, OC)
    weightScale = read_tensor(base_path + weightScale_tensor_data["node"] + ".bin", tuple(weightScale_tensor_data["shape"]))
    if zircon_workarounds["zircon_fx_fy_stride_workaround"]:
        weightScale = weightScale.permute(2, 3, 0, 1)  # Re-order to (IC / BLOCK_SIZE, OC, FY, FX)
        weightScale = F.pad(weightScale, pad=(0, 2, 0, 2))
        weightScale = weightScale.permute(2, 3, 0, 1)  # Re-order back to (FY, FX, IC / BLOCK_SIZE, OC)
    if zircon_workarounds["zircon_cgra_psum_workaround"] or zircon_workarounds["zircon_outer_reduction_tiling_workaround"]:
        weightScale = weightScale.permute(2, 0, 1, 3)
    if zircon_workarounds["k_dim_host_tiling"]:
        num_k_host_tiling_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
        k_dim_host_tiling_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        if len(weightScale.shape) == 2:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                weightScale = weightScale[:, slice_offset:slice_offset + slice_length]
            weightScale = weightScale.reshape((weightScale.shape[0], num_k_host_tiling_kernels, weightScale.shape[1] // num_k_host_tiling_kernels))
            weightScale = weightScale.permute(1, 0, 2)
        elif len(weightScale.shape) == 4:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                weightScale = weightScale[:, :, :, slice_offset:slice_offset + slice_length]
            weightScale = weightScale.reshape((weightScale.shape[0], weightScale.shape[1], weightScale.shape[2], num_k_host_tiling_kernels, weightScale.shape[3] // num_k_host_tiling_kernels))
            weightScale = weightScale.permute(3, 0, 1, 2, 4)
        else:
            raise NotImplementedError("K dimension host tiling is only supported for 2-D (GEMM) and 4-D (conv2d) weightScale tensors currently.")
        weightScale = weightScale[k_dim_host_tiling_idx]
    if zircon_workarounds["zircon_gemm_reduction_tiling_workaround"]:
        num_psums = zircon_workarounds["num_psums"]
        psum_idx = zircon_workarounds["psum_idx"]
        if len(weightScale.shape) == 2:
            # Tile along the reduction dimension, which is the outermost dimension for weightScale tensor
            weightScale = weightScale.reshape((num_psums, weightScale.shape[0] // num_psums, weightScale.shape[1]))
            weightScale = weightScale[psum_idx]
        else:
            raise NotImplementedError("Zircon GEMM reduction tiling workaround is only supported for 2-D (GEMM) weightScale tensors currently.")
    weightScale_e8m0 = float_to_e8m0(weightScale)

    return weightScale_e8m0

def parse_bias(base_path, bias_tensor_data, h2h_dir, zircon_workarounds, standalone_cgra_test=False):
    bias_shape = bias_tensor_data["shape"]
    for element in bias_shape:
        if element == 1:
            bias_shape.remove(element)
    bias = read_tensor(base_path + bias_tensor_data["node"] + ".bin", bias_shape)

    if zircon_workarounds["pad_oc"]:
        oc_dim = bias.shape[-1]
        padded_oc_dim = math.ceil(oc_dim / ZIRCON_MU_WORD_NUM_BYTES) * ZIRCON_MU_WORD_NUM_BYTES
        pad_size = padded_oc_dim - oc_dim
        bias = F.pad(bias, (0, pad_size), "constant", 0)
        print(f"INFO: Padded bias OC dimension from {oc_dim} to {padded_oc_dim} for fully connected layer.")

    if ((zircon_workarounds["zircon_cgra_psum_workaround"] or zircon_workarounds["zircon_outer_reduction_tiling_workaround"] or zircon_workarounds["zircon_gemm_reduction_tiling_workaround"]) and zircon_workarounds["psum_idx"] != 0):
        # If doing psum workaround, bias is zero for all but the 0th kernel
        # TODO: This should be improved in the future to just set the MU->has_bias config to false for such kernels
        bias = torch.zeros(tuple(bias_tensor_data["shape"]), dtype=torch.float32)
    if zircon_workarounds["k_dim_host_tiling"]:
        num_k_host_tiling_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
        k_dim_host_tiling_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        bias = bias.flatten()
        if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
            slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
            slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
            bias = bias[slice_offset:slice_offset + slice_length]
        bias = bias.reshape((num_k_host_tiling_kernels, bias.shape[0] // num_k_host_tiling_kernels))
        bias = bias[k_dim_host_tiling_idx]
    bias_bf16 = float32_to_bfloat16_bits(bias)

    if standalone_cgra_test:
        bias_bf16 = trim_channels_if_needed(bias_bf16)
        bias_bf16_be = bias_bf16.byteswap().newbyteorder('>')
        bias_bf16_be.tofile(f'{h2h_dir}/hw_bias_stencil.raw')

    return bias_bf16

def parse_residual(base_path, residual_tensor_data, h2h_dir, zircon_workarounds):
    # For conv2d, shape is in format: (B, Y, X, IC)
    residual = read_tensor(base_path + residual_tensor_data["node"] + ".bin", tuple(residual_tensor_data["shape"]))

    if zircon_workarounds["zircon_fx_fy_stride_workaround"]:
        residual = residual.permute(0, 3, 1, 2)  # Re-order to (B, IC, Y, X)
        residual_tmp = torch.zeros(residual.size(0), residual.size(1), 2*residual.size(2), 2*residual.size(3), device=residual.device, dtype=residual.dtype)
        # Place original values at odd indices (1, 3, 5, ...) using slicing
        residual_tmp[:, :, 1::2, 1::2] = residual
        residual = residual_tmp
        residual = residual.permute(0, 2, 3, 1)  # Re-order back to (B, Y, X, IC)

    if zircon_workarounds["zircon_input_act_padding_workaround"]:
        residual = residual.permute(0, 3, 1, 2)  # Re-order to (B, IC, Y, X)
        residual = F.pad(residual, pad=(0, zircon_workarounds["zircon_input_act_padding_workaround_size"], 0, zircon_workarounds["zircon_input_act_padding_workaround_size"]), value=-1000) # Pad with -1000 instead of 0s to catch potential bugs
        residual = residual.permute(0, 2, 3, 1)  # Re-order back to (B, Y, X, IC)

    # Tiling flow
    if zircon_workarounds["k_dim_host_tiling"] or zircon_workarounds["io_innermost_dim_tiling"]:
        if zircon_workarounds["k_dim_host_tiling"]:
            num_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
            kernel_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        else:
            num_kernels = zircon_workarounds["num_io_innermost_dim_tiling_kernels"]
            kernel_idx = zircon_workarounds["io_innermost_dim_tiling_idx"]

        tile_output_tensor = zircon_workarounds["output_tensor_k_dim_tiling"] or zircon_workarounds["output_tensor_io_innermost_dim_tiling"]

        # Divide the innermost dimension into num_kernels tiles and take the tile corresponding to kernel_idx
        # We don't know how many dimensions the tensor has, so we need code that handles different cases
        if len(residual.shape) == 2:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                residual = residual[:, slice_offset:slice_offset + slice_length]
            residual = residual.reshape((residual.shape[0], num_kernels, residual.shape[1] // num_kernels))
            residual = residual.permute(1, 0, 2)
        elif len(residual.shape) == 3:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                residual = residual[:, :, slice_offset:slice_offset + slice_length]
            residual = residual.reshape((residual.shape[0], residual.shape[1], num_kernels, residual.shape[2] // num_kernels))
            residual = residual.permute(2, 0, 1, 3)
        elif len(residual.shape) == 4:
            mha_permute = "MHA_PERMUTE" in os.environ and os.environ["MHA_PERMUTE"] == "1"
            if mha_permute:
                if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                    slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                    slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                    residual = residual[:, slice_offset:slice_offset + slice_length, :, :]
                num_attn_heads = int(os.environ.get("NUM_ATTENTION_HEADS", 12))
                # If MHA permute is on, then we tile long the head dimension, which is dim 1
                residual = residual.reshape((residual.shape[0], num_kernels, residual.shape[1] // num_kernels, residual.shape[2], residual.shape[3]))
                residual = residual.permute(1, 0, 2, 3, 4)

                # Make sure it worked correctly
                assert residual.shape[2] == num_attn_heads // num_kernels, f"Output tensor shape after k-dim tiling is {residual.shape}, expected head dimension to be {num_attn_heads // num_kernels}"
            else:
                if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                    slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                    slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                    residual = residual[:, :, :, slice_offset:slice_offset + slice_length]
                residual = residual.reshape((residual.shape[0], residual.shape[1], residual.shape[2], num_kernels, residual.shape[3] // num_kernels))
                residual = residual.permute(3, 0, 1, 2, 4)
        else:
            raise NotImplementedError("K dimension host tiling is only supported for 2-D, 3-D, and 4-D output tensors currently.")

        # If tile_output_tensor is not true, then make all elements not in kernel_idx tile 0, otherwise just take the kernel_idx tile
        if not(tile_output_tensor):
            mask = torch.zeros_like(residual)
            mask[..., kernel_idx, :] = 1
            residual = residual * mask
        else:
            residual = residual[kernel_idx]

    if zircon_workarounds["x_dim_host_tiling"]:
        x_dim_host_tiling_slice_offset = zircon_workarounds["x_dim_host_tiling_slice_offset"]
        x_dim_host_tiling_slice_length = zircon_workarounds["x_dim_host_tiling_slice_length"]
        num_x_host_tiling_kernels = zircon_workarounds["num_x_host_tiling_kernels"]
        x_dim_host_tiling_kernel_idx = zircon_workarounds["x_dim_host_tiling_idx"]
        # We don't know how many dimensions the tensor has, but we know that the X dimension is the second to last dimension, so we can write code that handles different cases based on the number of dimensions
        if len(residual.shape) == 3:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                residual = residual[:, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                residual = residual.reshape((residual.shape[0], num_x_host_tiling_kernels, residual.shape[1] // num_x_host_tiling_kernels, residual.shape[2]))
                residual = residual.permute(1, 0, 2, 3)
                residual = residual[x_dim_host_tiling_kernel_idx]
        elif len(residual.shape) == 4:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                residual = residual[:, :, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                residual = residual.reshape((residual.shape[0], residual.shape[1], num_x_host_tiling_kernels, residual.shape[2] // num_x_host_tiling_kernels, residual.shape[3]))
                residual = residual.permute(2, 0, 1, 3, 4)
                residual = residual[x_dim_host_tiling_kernel_idx]
        # Error out becuase it's not supported yet
        else:
            raise NotImplementedError("X dimension host tiling is not supported for non 3D or 4D tensors yet.")

    residual_bf16 = float32_to_bfloat16_bits(residual)
    residual_bf16_be = residual_bf16.byteswap().newbyteorder('>')

    # TODO: Probably need to add logic for zircon_outer_reduction_tiling_workaround here as well
    if (zircon_workarounds["zircon_gemm_reduction_tiling_workaround"] or zircon_workarounds["zircon_cgra_psum_workaround"]) and (zircon_workarounds["psum_idx"] == 0):
        residual_bf16_be.tofile(f'{h2h_dir}/hw_partial_sum_input_stencil.raw')
    # Write the residual_bf16_be to a raw file except for psum workaround middle kernels
    elif not ((zircon_workarounds["zircon_gemm_reduction_tiling_workaround"] or zircon_workarounds["zircon_cgra_psum_workaround"]) and zircon_workarounds["psum_idx"] != (zircon_workarounds["num_psums"] - 1)):
        residual_bf16_be.tofile(f'{h2h_dir}/hw_residual_input_stencil.raw')
    # Flatten residual_bf16 and convert to a python list
    residual_bf16 = residual_bf16.flatten().tolist()

    return residual_bf16

def parse_input_bf16_cgra(base_path, input_tensor_data, h2h_dir, zircon_workarounds, model, layer):
    # For conv2d, shape is in format: (B, Y, X, IC)
    input= read_tensor(base_path + input_tensor_data["node"] + ".bin", tuple(input_tensor_data["shape"]))

    # SOFTMAX HACK: Change all -inf values (generally, all values < -200) to -200.0
    if (model == 'bert' or model == 'llama_prefill') and 'softmax' in layer:
        input[input < -200.0] = -200.0

    if zircon_workarounds["zircon_input_act_padding_workaround"]:
        input = input.permute(0, 3, 1, 2)  # Re-order to (B, IC, Y, X)
        pad_dim = zircon_workarounds["zircon_input_act_padding_workaround_size"] * zircon_workarounds["zircon_input_act_padding_workaround_stride"]
        input = F.pad(input, pad=(0, pad_dim, 0, pad_dim)) # Pad X and Y dimensions with zeros
        input = input.permute(0, 2, 3, 1)  # Re-order back to (B, Y, X, IC)

    if zircon_workarounds["io_innermost_dim_tiling"]:
        if len(input.shape) == 3:
            num_io_innermost_dim_tiling_kernels = zircon_workarounds["num_io_innermost_dim_tiling_kernels"]
            io_innermost_dim_tiling_idx = zircon_workarounds["io_innermost_dim_tiling_idx"]
            input = input.reshape((input.shape[0], input.shape[1], num_io_innermost_dim_tiling_kernels, input.shape[2] // num_io_innermost_dim_tiling_kernels))
            input = input.permute(2, 0, 1, 3)
            input = input[io_innermost_dim_tiling_idx]
        elif len(input.shape) == 4:
            num_io_innermost_dim_tiling_kernels = zircon_workarounds["num_io_innermost_dim_tiling_kernels"]
            io_innermost_dim_tiling_idx = zircon_workarounds["io_innermost_dim_tiling_idx"]
            mha_concat = "MHA_CONCAT" in os.environ and os.environ["MHA_CONCAT"] == "1"
            if mha_concat:
                num_attention_heads = int(os.environ.get("NUM_ATTENTION_HEADS", 12))
                # If MHA concat is on, then we tile along the head dimension, which is dim 1
                input = input.reshape((input.shape[0], num_io_innermost_dim_tiling_kernels, input.shape[1] // num_io_innermost_dim_tiling_kernels, input.shape[2], input.shape[3]))
                input = input.permute(1, 0, 2, 3, 4)
                # Make sure it worked correctly
                assert input.shape[2] == num_attention_heads // num_io_innermost_dim_tiling_kernels
            else:
                input = input.reshape((input.shape[0], input.shape[1], input.shape[2], num_io_innermost_dim_tiling_kernels, input.shape[3] // num_io_innermost_dim_tiling_kernels))
                input = input.permute(3, 0, 1, 2, 4)
            input = input[io_innermost_dim_tiling_idx]
        else:
            raise NotImplementedError("I/O dimension 0 host tiling is only supported for 3D and 4D input tensors currently.")


    if zircon_workarounds["io_dim1_tiling"]:
        if len(input.shape) == 3:
            num_io_dim1_tiling_kernels = zircon_workarounds["num_io_dim1_tiling_kernels"]
            io_dim1_tiling_idx = zircon_workarounds["io_dim1_tiling_idx"]
            input = input.reshape((input.shape[0], num_io_dim1_tiling_kernels, input.shape[1] // num_io_dim1_tiling_kernels, input.shape[2]))
            input = input.permute(1, 0, 2, 3)
            input = input[io_dim1_tiling_idx]
        elif len(input.shape) == 4:
            num_io_dim1_tiling_kernels = zircon_workarounds["num_io_dim1_tiling_kernels"]
            io_dim1_tiling_idx = zircon_workarounds["io_dim1_tiling_idx"]
            input = input.reshape((input.shape[0], num_io_dim1_tiling_kernels, input.shape[1] // num_io_dim1_tiling_kernels, input.shape[2], input.shape[3]))
            input = input.permute(1, 0, 2, 3, 4)
            input = input[io_dim1_tiling_idx]
        else:
            raise NotImplementedError("I/O dimension 1 host tiling is only supported for 3D and 4D input tensors currently.")


    input_bf16_cgra = float32_to_bfloat16_bits(input)
    input_bf16_cgra = trim_channels_if_needed(input_bf16_cgra)
    input_bf16_cgra_be = input_bf16_cgra.byteswap().newbyteorder('>')
    input_bf16_cgra_be.tofile(f'{h2h_dir}/hw_input_stencil.raw')

    # Flatten input_bf16_cgra and convert to a python list
    input_bf16_cgra = input_bf16_cgra.flatten().tolist()


    return input_bf16_cgra

def parse_inputScale_e8m0_packed_cgra(base_path, inputScale_tensor_data, h2h_dir, zircon_workarounds):
    inputScale_e8m0_unpacked = parse_inputScale(base_path, inputScale_tensor_data, zircon_workarounds)

    if zircon_workarounds["io_innermost_dim_tiling"]:
        assert len(inputScale_e8m0_unpacked.shape) == 3, "I/O dimension 0 host tiling is only supported for 3D inputScale tensors."
        num_io_innermost_dim_tiling_kernels = zircon_workarounds["num_io_innermost_dim_tiling_kernels"]
        io_innermost_dim_tiling_idx = zircon_workarounds["io_innermost_dim_tiling_idx"]
        inputScale_e8m0_unpacked = np.array(inputScale_e8m0_unpacked)
        inputScale_e8m0_unpacked = inputScale_e8m0_unpacked.reshape((inputScale_e8m0_unpacked.shape[0], inputScale_e8m0_unpacked.shape[1], num_io_innermost_dim_tiling_kernels, inputScale_e8m0_unpacked.shape[2] // num_io_innermost_dim_tiling_kernels))
        inputScale_e8m0_unpacked = inputScale_e8m0_unpacked.permute(2, 0, 1, 3)
        inputScale_e8m0_unpacked = inputScale_e8m0_unpacked[io_innermost_dim_tiling_idx].tolist()

    inputScale_e8m0_packed = np.zeros((len(inputScale_e8m0_unpacked) // 2,), dtype=np.uint16)

    # Pack consecutive 2 e8m0 values into one uint16 with even indices as the low byte and odd indices as the high byte
    for i in range(0, len(inputScale_e8m0_unpacked), 2):
        low_byte = inputScale_e8m0_unpacked[i]
        high_byte = inputScale_e8m0_unpacked[i + 1] if (i + 1) < len(inputScale_e8m0_unpacked) else 0
        packed_value = (high_byte << 8) | low_byte
        inputScale_e8m0_packed[i // 2] = packed_value

    inputScale_e8m0_packed_be = inputScale_e8m0_packed.byteswap().newbyteorder('>')
    inputScale_e8m0_packed_be.tofile(f'{h2h_dir}/hw_input_scale_stencil.raw')

    return inputScale_e8m0_packed.tolist()

def parse_weight_bf16_cgra(base_path, weight_tensor_data, h2h_dir, zircon_workarounds):
    # For conv2d, shape is in format: (Y, X, IC, OC)
    weight = read_tensor(base_path + weight_tensor_data["node"] + ".bin", tuple(weight_tensor_data["shape"]))

    # Pad to multiple of 32
    if zircon_workarounds["pad_oc"]:
        assert len(weight.shape) == 2, "PAD_OC is only supported for fully connected layers with 2D weight tensors."
        oc_dim = weight.shape[0]
        padded_oc_dim = math.ceil(oc_dim / ZIRCON_MU_WORD_NUM_BYTES) * ZIRCON_MU_WORD_NUM_BYTES
        pad_size = padded_oc_dim - oc_dim
        weight = F.pad(weight, (0, 0, 0, pad_size), "constant", 0)
        print(f"INFO: Padded weight OC dimension from {oc_dim} to {padded_oc_dim} for fully connected layer.")


    if zircon_workarounds["k_dim_host_tiling"]:
        num_k_host_tiling_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
        k_dim_host_tiling_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        # Fully connected layers have 2D weight tensors
        if len(weight.shape) == 2:
            weight = weight.reshape((num_k_host_tiling_kernels, weight.shape[0] // num_k_host_tiling_kernels, weight.shape[1]))
        else:
            # throw exception
            exception_message = f"Error: K dimension host tiling is only supported for fully connected layers with 2D weight tensors in CGRA standalone test mode. Weight tensor shape: {weight.shape}"
            raise NotImplementedError(exception_message)

        weight = weight[k_dim_host_tiling_idx]

    weight_bf16_cgra = float32_to_bfloat16_bits(weight)
    weight_bf16_cgra = trim_channels_if_needed(weight_bf16_cgra)
    weight_bf16_cgra_be = weight_bf16_cgra.byteswap().newbyteorder('>')
    weight_bf16_cgra_be.tofile(f'{h2h_dir}/hw_weight_stencil.raw')

    # Flatten weight_bf16_cgra and convert to a python list
    weight_bf16_cgra = weight_bf16_cgra.flatten().tolist()

    return weight_bf16_cgra

def write_per_tensor_scales(tensor_metadata, base_path, output_dir):
    scales = {}
    for op in tensor_metadata["ops"]:
        op_name = op["name"]
        # Look for dequantize and quantize ops to find the names of the per-tensor scales
        if "dequantize_default" in op_name:
            dequantize_scale_file_name = op["kwargs"]["scale"]["tensor"]["node"]
            dequantize_scale = get_scale_from_bin(f"{base_path}{dequantize_scale_file_name}.bin")
            print(f"Read dequantize scale {dequantize_scale} from {base_path}{dequantize_scale_file_name}.bin")
            scales["dequantize_scale"] = dequantize_scale
        if "quantize_default" in op_name and "dequantize_default" not in op_name:
            quantize_scale_file_name = op["kwargs"]["scale"]["tensor"]["node"]
            # For quantize, take the reciprocal so we can still use fpmul
            quantize_scale = 1.0/get_scale_from_bin(f"{base_path}{quantize_scale_file_name}.bin")
            print(f"Read quantize scale {quantize_scale} from {base_path}{quantize_scale_file_name}.bin")
            scales["quantize_scale"] = quantize_scale

    with open(f"{output_dir}/per_tensor_scales.txt", "w") as f:
        for key in scales:
            f.write(f"{key}: {scales[key]}\n")

def write_attention_scale(tensor_metadata, base_path, output_dir):
    scale = None
    for op in tensor_metadata["ops"]:
        op_name = op["name"]
        # Look out for "div" in name
        if "div" in op_name or ("mul" in op_name and not("matmul" in op_name)):
            attention_scale_file_name = op["kwargs"]["other"]["tensor"]["node"]
            scale = get_scale_from_bin(f"{base_path}{attention_scale_file_name}.bin")
            # Take the reciprocal so we can use fpmul
            if "div" in op_name:
                scale = 1.0/scale

            print(f"Read attention scale {scale} from {base_path}{attention_scale_file_name}.bin")

    assert scale is not None, "Attention scale not found in tensor metadata."
    with open(f"{output_dir}/attention_scale.txt", "w") as f:
        f.write(f"{scale}\n")


def parse_output(model, layer, base_path, output_tensor_data, zircon_workarounds):
    if (
        (model == "bert" and (layer == "linear_mx_default_4" or layer == "gelu" or layer == "tanh"))
        or (model == "fakegemm" and (layer == "linear_default_1"))
        or (model == "resnet18" and layer == "submodule")
        or (model == "llama_prefill" and (layer == "linear_mx_default_4" or layer == "silu"))
    ):
        output_tensor, output_datatype = do_custom_validation(model, layer)
    else:
        output_tensor = read_tensor(base_path + output_tensor_data["node"] + ".bin", tuple(output_tensor_data["shape"]))

        output_datatype = output_tensor_data["dtype"]

    if zircon_workarounds["k_dim_host_tiling"] or zircon_workarounds["io_innermost_dim_tiling"]:
        if zircon_workarounds["k_dim_host_tiling"]:
            num_kernels = zircon_workarounds["num_k_host_tiling_kernels"]
            kernel_idx = zircon_workarounds["k_dim_host_tiling_idx"]
        else:
            num_kernels = zircon_workarounds["num_io_innermost_dim_tiling_kernels"]
            kernel_idx = zircon_workarounds["io_innermost_dim_tiling_idx"]

        tile_output_tensor = zircon_workarounds["output_tensor_k_dim_tiling"] or zircon_workarounds["output_tensor_io_innermost_dim_tiling"]

        # Divide the innermost dimension into num_kernels tiles and take the tile corresponding to kernel_idx
        # We don't know how many dimensions the tensor has, so we need code that handles different cases
        if len(output_tensor.shape) == 2:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                output_tensor = output_tensor[:, slice_offset:slice_offset + slice_length]
            output_tensor = output_tensor.reshape((output_tensor.shape[0], num_kernels, output_tensor.shape[1] // num_kernels))
            output_tensor = output_tensor.permute(1, 0, 2)
        elif len(output_tensor.shape) == 3:
            if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                output_tensor = output_tensor[:, :, slice_offset:slice_offset + slice_length]
            output_tensor = output_tensor.reshape((output_tensor.shape[0], output_tensor.shape[1], num_kernels, output_tensor.shape[2] // num_kernels))
            output_tensor = output_tensor.permute(2, 0, 1, 3)
        elif len(output_tensor.shape) == 4:
            mha_permute = "MHA_PERMUTE" in os.environ and os.environ["MHA_PERMUTE"] == "1"
            mha_concat = "MHA_CONCAT" in os.environ and os.environ["MHA_CONCAT"] == "1"
            if mha_permute:
                if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                    slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                    slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                    output_tensor = output_tensor[:, slice_offset:slice_offset + slice_length, :, :]
                num_attn_heads = int(os.environ.get("NUM_ATTENTION_HEADS", 12))
                # If MHA permute is on, then we tile long the head dimension, which is dim 1
                output_tensor = output_tensor.reshape((output_tensor.shape[0], num_kernels, output_tensor.shape[1] // num_kernels, output_tensor.shape[2], output_tensor.shape[3]))
                output_tensor = output_tensor.permute(1, 0, 2, 3, 4)

                # Make sure it worked correctly
                assert output_tensor.shape[2] == num_attn_heads // num_kernels, f"Output tensor shape after k-dim tiling is {output_tensor.shape}, expected head dimension to be {num_attn_heads // num_kernels}"


            elif mha_concat:
                num_attn_heads = int(os.environ.get("NUM_ATTENTION_HEADS", 12))
                # If MHA concat is on, we tile along head dimensions, which is dim 2
                output_tensor = output_tensor.reshape((output_tensor.shape[0], output_tensor.shape[1], num_kernels, output_tensor.shape[2] // num_kernels, output_tensor.shape[3]))
                output_tensor = output_tensor.permute(2, 0, 1, 3, 4)

                # Make sure it worked correctly
                assert output_tensor.shape[3] == num_attn_heads // num_kernels, f"Output tensor shape after MHA concat for k dim tiling is {output_tensor.shape}, expected head dimension to be {num_attn_heads // num_kernels}"

            else:
                if zircon_workarounds["k_dim_host_tiling_pre_slicing"]:
                    slice_offset = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_offset"]
                    slice_length = zircon_workarounds["k_dim_host_tiling_pre_slicing_slice_length"]
                    output_tensor = output_tensor[:, :, :, slice_offset:slice_offset + slice_length]
                output_tensor = output_tensor.reshape((output_tensor.shape[0], output_tensor.shape[1], output_tensor.shape[2], num_kernels, output_tensor.shape[3] // num_kernels))
                output_tensor = output_tensor.permute(3, 0, 1, 2, 4)
        else:
            raise NotImplementedError("K dimension host tiling is only supported for 2-D, 3-D, and 4-D output tensors currently.")

        # If tile_output_tensor is not true, then make all elements not in kernel_idx tile 0, otherwise just take the kernel_idx tile
        if not(tile_output_tensor):
            mask = torch.zeros_like(output_tensor)
            mask[..., kernel_idx, :] = 1
            output_tensor = output_tensor * mask
        else:
            output_tensor = output_tensor[kernel_idx]


    if zircon_workarounds["io_dim1_tiling"]:
        tile_output_tensor = zircon_workarounds["output_tensor_io_dim1_tiling"]
        if len(output_tensor.shape) == 3:
            num_io_dim1_tiling_kernels = zircon_workarounds["num_io_dim1_tiling_kernels"]
            io_dim1_tiling_idx = zircon_workarounds["io_dim1_tiling_idx"]
            output_tensor = output_tensor.reshape((output_tensor.shape[0], num_io_dim1_tiling_kernels, output_tensor.shape[1] // num_io_dim1_tiling_kernels, output_tensor.shape[2]))
            output_tensor = output_tensor.permute(1, 0, 2, 3)
        elif len(output_tensor.shape) == 4:
            num_io_dim1_tiling_kernels = zircon_workarounds["num_io_dim1_tiling_kernels"]
            io_dim1_tiling_idx = zircon_workarounds["io_dim1_tiling_idx"]
            output_tensor = output_tensor.reshape((output_tensor.shape[0], num_io_dim1_tiling_kernels, output_tensor.shape[1] // num_io_dim1_tiling_kernels, output_tensor.shape[2], output_tensor.shape[3]))
            output_tensor = output_tensor.permute(1, 0, 2, 3, 4)
        else:
            raise NotImplementedError("I/O dimension 1 host tiling is only supported for 3D and 4D output tensors currently.")

        if not(tile_output_tensor):
            mask = torch.zeros_like(output_tensor)
            mask[:, io_dim1_tiling_idx, :, :, :] = 1
            output_tensor = output_tensor * mask
        else:
            output_tensor = output_tensor[io_dim1_tiling_idx]

    if zircon_workarounds["x_dim_host_tiling"]:
        x_dim_host_tiling_slice_offset = zircon_workarounds["x_dim_host_tiling_slice_offset"]
        x_dim_host_tiling_slice_length = zircon_workarounds["x_dim_host_tiling_slice_length"]
        num_x_host_tiling_kernels = zircon_workarounds["num_x_host_tiling_kernels"]
        x_dim_host_tiling_kernel_idx = zircon_workarounds["x_dim_host_tiling_idx"]
        # We don't know how many dimensions the tensor has, but we know that the X dimension is the second to last dimension, so we can write code that handles different cases based on the number of dimensions
        if len(output_tensor.shape) == 3:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                output_tensor = output_tensor[:, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                output_tensor = output_tensor.reshape((output_tensor.shape[0], num_x_host_tiling_kernels, output_tensor.shape[1] // num_x_host_tiling_kernels, output_tensor.shape[2]))
                output_tensor = output_tensor.permute(1, 0, 2, 3)
                output_tensor = output_tensor[x_dim_host_tiling_kernel_idx]
        elif len(output_tensor.shape) == 4:
            if x_dim_host_tiling_slice_offset is not None and x_dim_host_tiling_slice_length is not None:
                output_tensor = output_tensor[:, :, x_dim_host_tiling_slice_offset:x_dim_host_tiling_slice_offset + x_dim_host_tiling_slice_length, :]
            else:
                output_tensor = output_tensor.reshape((output_tensor.shape[0], output_tensor.shape[1], num_x_host_tiling_kernels, output_tensor.shape[2] // num_x_host_tiling_kernels, output_tensor.shape[3]))
                output_tensor = output_tensor.permute(2, 0, 1, 3, 4)
                output_tensor = output_tensor[x_dim_host_tiling_kernel_idx]
        # Error out becuase it's not supported yet
        else:
            raise NotImplementedError("X dimension host tiling is not supported for non 3D or 4D tensors yet.")

    if output_datatype == "bfloat16":
        output = float32_to_bfloat16_bits(output_tensor)
        output = trim_channels_if_needed(output)
        return output.flatten().tolist()
    elif output_datatype == "int8":
        output = output_tensor.to(torch.int8)
        output = output.numpy().tobytes()
        output = trim_channels_if_needed(output)
        return list(output)
    elif output_datatype == "fp8_e8m0":
        output = float_to_e8m0(output_tensor)
        output = trim_channels_if_needed(output)
        return output.flatten().tolist()
    else:
        raise NotImplementedError(f"Output datatype {output_datatype} not supported.")




def write_output_tensor_to_hex(output_data, output_datatype, gold_dir, num_output_tensors):
    if output_datatype == "int8":
        write_list_to_hex(output_data, f"{gold_dir}/gold_activation.txt", add_metadata=False, hex_width=2)
    elif output_datatype == "fp8_e8m0":
        if num_output_tensors > 1:
            e8m0_filename = f"{gold_dir}/gold_scale.txt"
        else:
            e8m0_filename = f"{gold_dir}/gold_activation.txt"
        write_list_to_hex(output_data, e8m0_filename, add_metadata=False, hex_width=2)
    elif output_datatype == "bfloat16":
        write_list_to_hex(output_data, f"{gold_dir}/gold_activation.txt", add_metadata=False, hex_width=4)
    else:
        raise NotImplementedError(f"Output datatype {output_datatype} not supported for writing to hex.")

def parse_tensors(model, layer, datatype, h2h_dir, debug_mode, per_tensor_scaling=False, attention_scaling=False, standalone_cgra_test=False):
    # Base path for the binary files
    base_path = f'/aha/voyager/test/compiler/networks/{model}/{datatype}/tensor_files/'

    with open("/aha/voyager/tensor_metadata.json", "r") as f:
        tensor_metadata = json.load(f)

    has_input = tensor_metadata["has_input"]
    has_weight = tensor_metadata["has_weight"]
    has_input_scale = tensor_metadata["has_input_scale"]
    has_weight_scale = tensor_metadata["has_weight_scale"]
    has_bias = tensor_metadata["has_bias"]
    has_residual = tensor_metadata["has_residual"]

    zircon_workarounds = parse_zircon_workarounds()

    # INPUT
    if has_input:
        input_tensor_data = tensor_metadata["ops"][0]["kwargs"]["input"]["tensor"]
        if not(standalone_cgra_test):
            input_start_addr = input_tensor_data["glb_base_address"]
            input_int8 = parse_input(base_path, input_tensor_data, zircon_workarounds)
        else:
            input_bf16_cgra = parse_input_bf16_cgra(base_path, input_tensor_data, h2h_dir, zircon_workarounds, model, layer)

    # INPUT SCALE
    if has_input_scale:
        if not(standalone_cgra_test):
            inputScale_tensor_data = tensor_metadata["ops"][0]["kwargs"]["input_scale"]["tensor"]
            inputScale_start_addr = inputScale_tensor_data["glb_base_address"]
            inputScale_e8m0 = parse_inputScale(base_path, inputScale_tensor_data, zircon_workarounds)
        else:
            inputScale_tensor_data = tensor_metadata["ops"][0]["kwargs"]["scale"]["tensor"]
            inputScale_e8m0_packed_cgra = parse_inputScale_e8m0_packed_cgra(base_path, inputScale_tensor_data, h2h_dir, zircon_workarounds)

    # WEIGHT
    if has_weight:
        weight_tensor_data = tensor_metadata["ops"][0]["kwargs"]["weight"]["tensor"]
        if not(standalone_cgra_test):
            weight_start_addr = weight_tensor_data["glb_base_address"]
            weight_int8 = parse_weight(base_path, weight_tensor_data, zircon_workarounds)
        else:
            weight_bf16_cgra = parse_weight_bf16_cgra(base_path, weight_tensor_data, h2h_dir, zircon_workarounds)

    # WEIGHT SCALE
    if has_weight_scale:
        weightScale_tensor_data = tensor_metadata["ops"][0]["kwargs"]["weight_scale"]["tensor"]
        weightScale_start_addr = weightScale_tensor_data["glb_base_address"]
        weightScale_e8m0 = parse_weightScale(
            base_path, weightScale_tensor_data, zircon_workarounds)

    # BIAS
    if has_bias:
        bias_tensor_data = tensor_metadata["ops"][0]["kwargs"]["bias"]["tensor"]
        if not(standalone_cgra_test):
            bias_start_addr = bias_tensor_data["glb_base_address"]
            bias_bf16 = parse_bias(base_path, bias_tensor_data, h2h_dir, zircon_workarounds, standalone_cgra_test)
        else:
            bias_bf16_cgra = parse_bias(base_path, bias_tensor_data, h2h_dir, zircon_workarounds, standalone_cgra_test)

    # RESIDUAL
    if has_residual:
        all_op_names = []
        for op in tensor_metadata["ops"]:
            all_op_names.append(op["name"])

        for op in tensor_metadata["ops"]:
            if "add" in op["name"]:
                for key in op["kwargs"]:
                    if "tensor" in op["kwargs"][key]:
                        # Slightly fragile, but we assume the residual tensor is the one that is not in the list of all op names
                        # May need to revisit this in the future...
                        # Also skipping dropout nodes b/c training is turned off right now
                        if (op["kwargs"][key]["tensor"]["node"] not in all_op_names) and ("dropout" not in op["kwargs"][key]["tensor"]["node"]):
                            residual_tensor_data = op["kwargs"][key]["tensor"]
                            break
        residual_bf16 = parse_residual(base_path, residual_tensor_data, h2h_dir, zircon_workarounds)

    # OUTPUT(s)
    if "tensors" in tensor_metadata["outputs"][0]:
        all_output_tensors = tensor_metadata["outputs"][0]["tensors"]
    else:
        all_output_tensors = tensor_metadata["outputs"]

    for output_tensor_data in all_output_tensors:
        num_output_tensors = len(all_output_tensors)
        output_data = parse_output(model, layer, base_path, output_tensor_data, zircon_workarounds)

        # gold_dir = f'/aha/voyager/compiled_collateral/{model}-{layer}/compare/'
        gold_dir = f'/aha/voyager/'
        # FIXME
        write_output_tensor_to_hex(output_data, output_tensor_data["dtype"], gold_dir, num_output_tensors)



    tensor_files_dir = f'/aha/voyager/compiled_collateral/{model}-{layer}/tensor_files/'

    # Per tensor scaling factors (read them and write out as floating point values)
    if per_tensor_scaling:
        write_per_tensor_scales(tensor_metadata, base_path, tensor_files_dir)

    # Attention scaling factor (read and write out as floating point value)
    if attention_scaling:
        write_attention_scale(tensor_metadata, base_path, tensor_files_dir)

    torch.set_printoptions(precision=10)

    # For psum_workoround, if not kernel 0, read prior kernel output from text file and convert to raw binary file
    if zircon_workarounds["zircon_cgra_psum_workaround"] and (zircon_workarounds["psum_idx"] != 0):
        if zircon_workarounds["non_uniform_slicing"]:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_psum_reduction_fp/{model}-{layer}_slice_{zircon_workarounds["non_uniform_slice_idx"]}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        else:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_psum_reduction_fp/{model}-{layer}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        assert os.path.exists(hw_output_txt_path), f"The prior kernel output file {hw_output_txt_path} does not exist."
        # For the last psum, write to hw_residual_input_stencil.raw, otherwise write to hw_partial_sum_input_stencil.raw
        if zircon_workarounds["psum_idx"] == (zircon_workarounds["num_psums"] - 1):
            hw_output_raw_path = f'{h2h_dir}/hw_residual_input_stencil.raw'
        else:
            hw_output_raw_path = f'{h2h_dir}/hw_partial_sum_input_stencil.raw'
        hw_output_txt_to_raw(hw_output_txt_path, hw_output_raw_path)

    # For outer channel tiling workaround, if not kernel 0, read prior kernel output from text file and convert to raw binary file
    if zircon_workarounds["zircon_outer_reduction_tiling_workaround"] and (zircon_workarounds["psum_idx"] != 0):
        if zircon_workarounds["non_uniform_slicing"]:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_psum_reduction_fp/per_tensor_{model}-{layer}_slice_{zircon_workarounds["non_uniform_slice_idx"]}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        else:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_psum_reduction_fp/per_tensor_{model}-{layer}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        assert os.path.exists(hw_output_txt_path), f"The prior kernel output file {hw_output_txt_path} does not exist."
        # For the last psum, write to hw_residual_input_stencil.raw, otherwise write to hw_partial_sum_input_stencil.raw
        if zircon_workarounds["psum_idx"] == (zircon_workarounds["num_psums"] - 1):
            hw_output_raw_path = f'{h2h_dir}/hw_residual_input_stencil.raw'
        else:
            hw_output_raw_path = f'{h2h_dir}/hw_partial_sum_input_stencil.raw'
        hw_output_txt_to_raw(hw_output_txt_path, hw_output_raw_path)

    # For gemm reduction tiling workaround, if not kernel 0, read prior kernel output from text file and convert to raw binary file
    if zircon_workarounds["zircon_gemm_reduction_tiling_workaround"] and (zircon_workarounds["psum_idx"] != 0):
        if (model == "bert" and layer == "gelu") or (model == "llama_prefill" and layer == "silu"):
            layer = "linear_mx_default_4"
        if (model == "llama_prefill" and layer == "mul_9"):
            layer = "submodule_40"
        if zircon_workarounds["non_uniform_slicing"]:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_2d_psum_reduction_fp/{model}-{layer}_slice_{zircon_workarounds["non_uniform_slice_idx"]}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        else:
            hw_output_txt_path = f'/aha/Halide-to-Hardware/apps/hardware_benchmarks/apps/zircon_2d_psum_reduction_fp/{model}-{layer}_gold/kernel_{zircon_workarounds["intermediate_gold_idx"] - 1}_output.txt'
        assert os.path.exists(hw_output_txt_path), f"The prior kernel output file {hw_output_txt_path} does not exist."
        # TODO: Only do this if there IS a residual
        # # For the last psum, write to hw_residual_input_stencil.raw, otherwise write to hw_partial_sum_input_stencil.raw
        # if zircon_workarounds["psum_idx"] == (zircon_workarounds["num_psums"] - 1):
        #     hw_output_raw_path = f'{h2h_dir}/hw_residual_input_stencil.raw'
        # else:
        #     hw_output_raw_path = f'{h2h_dir}/hw_partial_sum_input_stencil.raw'
        hw_output_raw_path = f'{h2h_dir}/hw_partial_sum_input_stencil.raw'
        hw_output_raw_path_plus_bin = f'{h2h_dir}/bin/hw_partial_sum_input_stencil.raw'
        hw_output_txt_to_raw(hw_output_txt_path, hw_output_raw_path)
        if os.path.exists(f'{h2h_dir}/bin/'):
            hw_output_txt_to_raw(hw_output_txt_path, hw_output_raw_path_plus_bin)


    if debug_mode:
        debug_print_tensors(input, input_int8, bias_bf16, inputScale_e8m0, weightScale_e8m0)

    # Write the tensors to hex files in tensor_files directory
    write_all_in_tensors_to_hex(
        tensor_files_dir,
        input_int8=input_int8 if has_input and not(standalone_cgra_test) else None,
        input_bf16_cgra=input_bf16_cgra if has_input and standalone_cgra_test else None,
        weight_int8=weight_int8 if has_weight and not(standalone_cgra_test) else None,
        weight_bf16_cgra=weight_bf16_cgra if has_weight and standalone_cgra_test else None,
        bias_bf16=bias_bf16 if has_bias and not(standalone_cgra_test) else None,
        bias_bf16_cgra=bias_bf16_cgra if has_bias and standalone_cgra_test else None,
        inputScale_e8m0=inputScale_e8m0 if has_input_scale and not(standalone_cgra_test) else None,
        inputScale_e8m0_packed_cgra=inputScale_e8m0_packed_cgra if has_input_scale and standalone_cgra_test else None,
        weightScale_e8m0=weightScale_e8m0 if has_weight_scale else None,
        residual_bf16=residual_bf16 if has_residual else None,
        input_start_addr=input_start_addr if has_input and not(standalone_cgra_test) else 0,
        weight_start_addr=weight_start_addr if has_weight and not(standalone_cgra_test) else 0,
        bias_start_addr=bias_start_addr if has_bias and not(standalone_cgra_test) else 0,
        inputScale_start_addr=inputScale_start_addr if has_input_scale and not(standalone_cgra_test) else 0,
        weightScale_start_addr=weightScale_start_addr if has_weight_scale else 0,
    )

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Parse DNN layer tensors from binary files and convert them to hex files.')
    parser.add_argument('--model', type=str, required=True, help='Model name (e.g., resnet18)')
    parser.add_argument('--layer', type=str, required=True, help='Layer name (e.g., conv2d_mx_default_11)')
    parser.add_argument('--datatype', type=str, default='MXINT8', help='Data type of the tensors')
    parser.add_argument('--h2h_dir', type=str, required=True, default='/aha/Halide-to-Hardware/', help='Path to Halide-to-Hardware directory')
    parser.add_argument('--debug', action='store_true', help='Enable debug mode to print tensor values')
    parser.add_argument('--per-tensor-scaling', action='store_true', help='Read and dump scales for per-tensor scaling (default is microscaling)')
    parser.add_argument('--attention-scaling', action='store_true', help='Enable attention scaling for a layer')
    parser.add_argument('--standalone-cgra-test', action='store_true', help='Enable standalone CGRA test mode')

    args = parser.parse_args()

    parse_tensors(args.model, args.layer, args.datatype, args.h2h_dir, args.debug, per_tensor_scaling=args.per_tensor_scaling, attention_scaling=args.attention_scaling, standalone_cgra_test=args.standalone_cgra_test)