build_params = {
    "datatype": "INT8",
    "ic_dimension": 16,
    "oc_dimension": 16,
    "technology": "intel16",
    "clock_period": 1,
}

sim_params = {
    "sims": "accelerator,systemc",
    "network": "resnet18",  # default network
    "layer": "quantize_symmetric",  # default layer
}

sweep_params = {
    "datatypes": ["E4M3", "BF16", "P8_1"],
    # "dimensions": [[16, 16], [16, 32], [32, 32]],
    "dimensions": [16, 32],
    "tests": {
        "resnet18": [
            "quantize_symmetric",
            "submodule_0",
            "max_pool2d",
            "quantize_symmetric_1",
            "submodule_1",
            "submodule_2",
            "quantize_symmetric_3",
            "submodule_3",
            "submodule_4",
            "submodule_5",
            "conv2d_6",
            "submodule_6",
            "quantize_symmetric_7",
            "submodule_7",
            "submodule_8",
            "submodule_9",
            "conv2d_11",
            "submodule_10",
            "quantize_symmetric_11",
            "submodule_11",
            "submodule_12",
            "submodule_13",
            "conv2d_16",
            "submodule_14",
            "quantize_symmetric_15",
            "submodule_15",
            "submodule_16",
            "adaptive_avg_pool2d",
            "linear",
        ],
        "mobilebert_encoder": [
            "quantize_symmetric",
            "submodule_0",
            "submodule_1",
            "quantize_symmetric_1",
            "submodule_2",
            "submodule_3",
            "submodule_4",
            "submodule_15",
            "softmax_1",
            "quantize_symmetric_21",
            "matmul_6",
            "submodule_16",
            "softmax_2",
            "quantize_symmetric_22",
            "matmul_7",
            "submodule_17",
            "softmax_3",
            "quantize_symmetric_23",
            "matmul_8",
            "submodule_18",
            "softmax_4",
            "quantize_symmetric_24",
            "matmul_9",
            "submodule_20",
            "submodule_5",
            "add_4",
            "quantize_symmetric_7",
            "submodule_6",
            "submodule_7",
            "add_6",
            "quantize_symmetric_9",
            "submodule_8",
            "submodule_9",
            "add_8",
            "quantize_symmetric_11",
            "submodule_10",
            "submodule_11",
            "add_10",
            "quantize_symmetric_13",
            "submodule_12",
            "quantize_symmetric_14",
            "submodule_13",
            "submodule_19",
            "submodule_14",
            "add_14",
        ],
    },
}
