#=========================================================================
# Intel Memory
#=========================================================================
# Author : Kathleen Feng
# Date   : 19 October 2023
#

name: memory

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - ./run.sh

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
parameters:
  memory_name: undefined
