#=========================================================================
# Constraints
#=========================================================================

name: constraints

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------
outputs:
  - constraints.tcl

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
