#####################################
### ResNet Codegen Layer by Layer ###
#####################################

ResNet Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    # - python3 -m venv venv
    # - . ./venv/bin/activate
    # - pip3 install -r zagzig/requirements.txt
    # - pip3 install -r requirements.txt
    - (cd zagzig/proto && ./gen.sh)
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k)
    - export LD_LIBRARY_PATH=/cad/mentor/2021.1/Mgc_home/shared/lib/
    - python3 run_tests.py --use_codegen --model resnet18 --data_dir test/codegen/gen_data/ --simulators fp32,file --tolerance 0.01

ResNet Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    # - python3 -m venv venv
    # - . ./venv/bin/activate
    # - pip3 install -r zagzig/requirements.txt
    # - pip3 install -r requirements.txt
    - (cd zagzig/proto && ./gen.sh)
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k)
    - export LD_LIBRARY_PATH=/cad/mentor/2021.1/Mgc_home/shared/lib/
    - python3 run_tests.py --use_codegen --model resnet18 --data_dir test/codegen/gen_data/ --simulators accelerator,customposit --tolerance 0.01
# ########################
# ### ResNet End 2 End ###
# ########################

# ResNet Codegen End2End (FP32 Gold Model vs. Pytorch):
#   stage: test
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive
#   artifacts:
#     when: always
#     paths:
#       - ./test_outputs
#     expire_in: 1 week
#   script:
#     # - python3 -m venv venv
#     # - . ./venv/bin/activate
#     # - pip3 install -r zagzig/requirements.txt
#     # - pip3 install -r requirements.txt
#     - (cd zagzig/proto && ./gen.sh)
#     - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k)
#     - export LD_LIBRARY_PATH=/cad/mentor/2021.1/Mgc_home/shared/lib/
#     - mkdir ./test_outputs
#     - make -j8 BASE_FLAGS='-DUSE_CODEGEN' clean TestRunner
#     - make BASE_FLAGS='-DUSE_CODEGEN' TestRunner
#     - DATA_DIR=./test/resnet/gen_data/ TOLERANCE=0.01 NETWORK=resnet TESTS=Conv_0,Gemm_48 SIMS=fp32,file ./build/TestRunner

# ResNet Codegen End2End (Accel vs. Posit Gold Model):
#   stage: test
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive
#   artifacts:
#     when: always
#     paths:
#       - ./test_outputs
#     expire_in: 1 week
#   script:
#     # - python3 -m venv venv
#     # - . ./venv/bin/activate
#     # - pip3 install -r zagzig/requirements.txt
#     # - pip3 install -r requirements.txt
#     - (cd zagzig/proto && ./gen.sh)
#     - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k)
#     - export LD_LIBRARY_PATH=/cad/mentor/2021.1/Mgc_home/shared/lib/
#     - mkdir ./test_outputs
#     - make -j8 BASE_FLAGS='-DUSE_CODEGEN' clean TestRunner
#     - make BASE_FLAGS='-DUSE_CODEGEN' TestRunner
#     - DATA_DIR=./test/resnet/gen_data/ TOLERANCE=0.15 NETWORK=resnet TESTS=Conv_0,Gemm_48 SIMS=customposit,accelerator ./build/TestRunner
