Setup Conda:
  stage: setup
  before_script:
    - export PATH=$HOME/miniforge3/condabin:$PATH
    - source $(conda info --base)/etc/profile.d/conda.sh
  script:
    - conda env create -p /sim/gitlab-runner/envs/ci-env-$CI_PIPELINE_ID -f $(pwd)/environment.yml
    - conda activate /sim/gitlab-runner/envs/ci-env-$CI_PIPELINE_ID
  rules:
    - when: always
