#########################################
### MobileBERT Codegen Layer by Layer ###
#########################################

MobileBERT Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --rram_banks 6 --test_type layerbylayer

MobileBERT Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --rram_banks 6 --test_type layerbylayer

MobileBERT Single Encoder Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert_single_enc.onnx)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --test_type layerbylayer

MobileBERT Single Encoder Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert_single_enc.onnx)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --test_type layerbylayer

####################################
### MobileBERT Codegen End 2 End ###
####################################

MobileBERT Codegen End2End (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --rram_banks 6 --test_type end2end

MobileBERT Codegen End2End (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --rram_banks 6 --test_type end2end

MobileBERT Single Encoder Codegen End2End (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert_single_enc.onnx)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --test_type end2end

MobileBERT Single Encoder Codegen End2End (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert_single_enc.onnx)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --test_type end2end

###################################
### MobileBERT Codegen Accuracy ###
###################################

MobileBERT Codegen Accuracy (FP32 Gold Model and Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6 --samples 128)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --rram_banks 6 --test_type accuracy --accuracy_tolerance 0.90

MobileBERT Codegen Accuracy (Accel and Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir ../data/glue/sst2 --model_path zagzig/models/onnx/mobilebert.onnx --rram_banks 6 --samples 64)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --rram_banks 6 --test_type accuracy --accuracy_tolerance 0.89
