#########################################
### MobileBERT Codegen Layer by Layer ###
#########################################

MobileBERT Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert.onnx --frontend naive_transformer --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01 --rram_banks 6

MobileBERT Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert.onnx --frontend naive_transformer --rram_banks 6)
    - python3 run_tests.py --model mobilebert_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01 --rram_banks 6

MobileBERT Single Encoder Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert_single_enc.onnx --frontend naive_transformer)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators fp32,file --tolerance 0.01

MobileBERT Single Encoder Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert_single_enc.onnx --frontend naive_transformer)
    - python3 run_tests.py --model mobilebert_single_enc_codegen --data_dir test/mobilebert/gen_data/ --simulators accelerator,customposit --tolerance 0.01

####################################
### MobileBERT Codegen End 2 End ###
####################################

MobileBERT Codegen End2End (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert.onnx --frontend naive_transformer)
    - mkdir ./test_outputs
    - make -j8 clean TestRunner
    - make TestRunner
    - DATA_DIR=test/mobilebert/gen_data/ TOLERANCE=0.01 NETWORK=mobilebert_codegen TESTS=mobilebert_encoder_layer_0_attention_self_value_MatMul,mobilebert_pooler_Gather SIMS=fp32,file ./build/TestRunner

MobileBERT Codegen End2End (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir /pool0/fpedd/su/imagenet/val_1k --model_path zagzig/models/onnx/mobilebert.onnx --frontend naive_transformer)
    - mkdir ./test_outputs
    - make -j8 clean TestRunner
    - make TestRunner
    - DATA_DIR=test/mobilebert/gen_data/ TOLERANCE=0.01 NETWORK=mobilebert_codegen TESTS=mobilebert_encoder_layer_0_attention_self_value_MatMul,mobilebert_pooler_Gather SIMS=customposit,accelerator ./build/TestRunner
