#####################################
### ResNet Codegen Layer by Layer ###
#####################################

ResNet Codegen Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir data/imagenet --model_path zagzig/models/onnx/resnet18.onnx --frontend zigzag)
    - python3 run_tests.py --model resnet18_codegen --data_dir test/resnet/gen_data/ --simulators fp32,file --tolerance 0.01

ResNet Codegen Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir data/imagenet --model_path zagzig/models/onnx/resnet18.onnx --frontend zigzag)
    - python3 run_tests.py --model resnet18_codegen --data_dir test/resnet/gen_data/ --simulators accelerator,customposit --tolerance 0.01

################################
### ResNet Codegen End 2 End ###
################################

ResNet Codegen End2End (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir data/imagenet --model_path zagzig/models/onnx/resnet18.onnx --frontend zigzag)
    - mkdir -p ./test_outputs
    - make clean
    - make -j8 TestRunner
    - make TestRunner
    - DATA_DIR=test/resnet/gen_data/ TOLERANCE=0.01 NETWORK=resnet18_codegen TESTS=Conv_0,Gemm_48 SIMS=fp32,file ./build/TestRunner

ResNet Codegen End2End (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - (cd zagzig && python3 run_zagzig.py --data_dir data/imagenet --model_path zagzig/models/onnx/resnet18.onnx --frontend zigzag)
    - mkdir -p ./test_outputs
    - make clean
    - make -j8 TestRunner
    - make TestRunner
    - DATA_DIR=test/resnet/gen_data/ TOLERANCE=0.01 NETWORK=resnet18_codegen TESTS=Conv_0,Gemm_48 SIMS=customposit,accelerator ./build/TestRunner
