#############################
### ResNet Layer by Layer ###
#############################

ResNet Layers (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - python3 models/resnet/gen_resnet_data.py
    - python3 run_tests.py --simulators fp32,file --tolerance 0.01

ResNet Layers (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - python3 models/resnet/gen_resnet_data.py
    - python3 run_tests.py --simulators accelerator,customposit --tolerance 0.01

########################
### ResNet End 2 End ###
########################

ResNet End2End (FP32 Gold Model vs. Pytorch):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - python3 models/resnet/gen_resnet_data.py
    - mkdir -p ./test_outputs
    - make clean
    - make -j8 TestRunner
    - make TestRunner
    - TOLERANCE=0.01 NETWORK=resnet TESTS=conv1,fc SIMS=fp32,file ./build/TestRunner

ResNet End2End (Accel vs. Posit Gold Model):
  stage: test
  artifacts:
    when: always
    paths:
      - ./test_outputs
    expire_in: 1 week
  script:
    - python3 models/resnet/gen_resnet_data.py
    - mkdir -p ./test_outputs
    - make clean
    - make -j8 TestRunner
    - make TestRunner
    - TOLERANCE=0.15 NETWORK=resnet TESTS=conv1,fc SIMS=customposit,accelerator ./build/TestRunner